### PR TITLE
Incorporate enzyme tests for instance ui

### PR DESCRIPTION
**Pull request by y-kkamil**
**Description**

Changes proposed in this pull request:

- Enable e2e catalog ui tests
- Delete unstable instances UI e2e test 
- Instances UI is already tested via enzyme tests

**Related issue(s)**
https://github.com/kyma-project/console/issues/1295

### CODE REVIEW

**Comment by kwiatekus** [comment]
Re-enabling stable ui tests for catalog.
Build history for this PR:
https://status.build.kyma-project.io/?repo=kyma-project%2Fkyma&type=presubmit&pull=5950

**Comment by kwiatekus** [comment]
already 3 successful runs in a row.
Lets go for another one

/test all

**Comment by sjanota** [comment]
/test 
pre-master-kyma-gke-integration

**Comment by sjanota** [comment]
Catalog tests have passed 3 times in a row without crash

**Pull request merged**
