### PR TITLE
Apply new defaults for kyma 2

### PR DESCRIPTION
**Pull request by a-thaler**
**Description**
As the main branch is the new kyma2 baseline for releasing, it is time to apply the kyma2 specific defaults to the main branch and remove the temporary `installation/resources/values.yaml` file. So the file should be applied to the individual charts and the file can be removed.

Changes proposed in this pull request:

- applied all settings of the file to the individual charts
- removed the file

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/11337
https://github.com/kyma-project/kyma/pull/11976

### CODE REVIEW

**Review by strekm — APPROVED** [review]
/meow

**Review by m00g3n — APPROVED** [review]
LGTM

**Review by skhalash — APPROVED** [review]

**Review by piotrmiskiewicz — APPROVED** [review]

**Review by piotrmiskiewicz — APPROVED** [review]

**Pull request merged**
