### PR TITLE
Upgrade Knative Serving to v0.5.1

### PR DESCRIPTION
**Pull request by JoergBastian**
**Description**

Changes proposed in this pull request:

- Upgrade Knative Serving component from version 0.4.1 to 0.5.0

**Related issue(s)**
Depends on / builds up on PR #3228

### CODE REVIEW

**Comment by abbi-gaurav** [comment]
@JoergBastian , we should also update Knative eventing to the same version.

**Comment by k15r** [comment]
outdated, closing

**Pull request closed without merging**
