### PR TITLE
Fullfill stub for webhooks

### PR DESCRIPTION
**Pull request by dbadura**
**Description**
When serverless's CRD and serverless's yaml are applied together, the configuration of webhook is not yes initialized.
To prevent user from applying not defaulted correct function CR, the mutating and validation webhook configuration is fulfilled without CABundle.
Changes proposed in this pull request:

- add configuration for mutating webhook
- add configuration for validating webhook

**Related issue(s)**
[](https://github.com/kyma-project/kyma/issues/17147)

### CODE REVIEW

**Comment by dbadura** [comment]
> @dbadura this doesnt help with initial crash of serverless webhook
> 
> ```
> kyma deploy -s PR-17187 --component serverless
> ```
> 
> ```
> kyma-system   serverless-webhook-svc-5f66bbd9d7-5bz9d   0/1     Running             0          17s
> kyma-system   serverless-webhook-svc-5f66bbd9d7-5bz9d   0/1     Error               0          23s
> kyma-system   serverless-webhook-svc-5f66bbd9d7-5bz9d   0/1     Running             1 (1s ago)   24s
> ```

It won't help with this problem, because it solvs other problem when you can apply plain function CR between applying the CRD and webhook config configuration by webhook

**Comment by kwiatekus** [comment]
This helps fixing controller panic on nil upon premature function CR creation.
Those changes do not let the non-defaulted function CR pass  simply because the admission verification are enforced.

```
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/kwiatekus/serverless-keda-demo/main/demo-app/fibo-fn.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.serverless.kyma-project.io": failed to call webhook: Post "https://serverless-webhook.kyma-system.svc:443/defaulting/functions?timeout=10s": no endpoints available for service "serverless-webhook"
```

**Review by anoipm — APPROVED** [review]

**Pull request merged**
