### PR TITLE
Add description field to test definition CR

### PR DESCRIPTION
**Pull request by tobiscr**
**Description**

Adding a field to add a description to a test definition resource.

**Related issue(s)**

### CODE REVIEW

**Review by clebs — APPROVED** [review]

**Comment by PK85** [comment]
@tobiscr of course, that improvement make sense. Please update main project too, see: https://github.com/kyma-incubator/octopus/

Especially:
- CRD: https://github.com/kyma-incubator/octopus/blob/master/chart/octopus/templates/testing_v1alpha1_testdefinition.yaml#L31
- Documentation: https://github.com/kyma-incubator/octopus/blob/master/docs/crd-test-definition.md#custom-resource-parameters
- Example: https://github.com/kyma-incubator/octopus/blob/master/config/samples/testdefinition.yaml which is used in the tutorial: https://github.com/kyma-incubator/octopus/blob/master/docs/tutorial.md

**Review by PK85 — CHANGES_REQUESTED** [review]
see above comment.

**Review by PK85 — APPROVED** [review]

**Comment by tobiscr** [comment]
> see above comment.

PR to address this is open: https://github.com/kyma-incubator/octopus/pull/46

**Review by suleymanakbas91 — APPROVED** [review]

**Review by clebs — APPROVED** [review]

**Pull request merged**
