### PR TITLE
Release 1.18.0-rc2

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- installer bumped to 1.18.0-rc2
- rafter - https://github.com/kyma-project/kyma/pull/10166 - e814b1c93e70ec708b76e3b1d19e85fc0d512651
- service-catalog - https://github.com/kyma-project/kyma/pull/10177 - 92660ceca74b6eacad027be6738a85708093da58
- istio-proxy-reset - https://github.com/kyma-project/kyma/pull/10173 - a1466442ef3b0a39c46aec7dab0596002eb18d25
- ory-security-fix - https://github.com/kyma-project/kyma/pull/10164 - 383d415c1f72105efc268e30c3f398ef32ef9629
- kiali evaluation - https://github.com/kyma-project/kyma/pull/10172 - 167118ab133b44754cd3a15c558403c865ce8851

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/10118

### CODE REVIEW

**Review by strekm — APPROVED** [review]
/meow

**Review by suleymanakbas91 — APPROVED** [review]

**Review by crabtree — APPROVED** [review]

**Review by m00g3n — APPROVED** [review]

**Pull request merged**
