### PR TITLE
Bump dependencies for eventing controller and epp

### PR DESCRIPTION
**Pull request by raypinto**
**Description**

Changes proposed in this pull request:

- Bump base image in dockerfile for both epp and ec
- Bump nats server and client version for both epp and ec
- Added replace for api-gateway for epp 

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/15983 https://github.com/kyma-project/kyma/pull/15970 https://github.com/kyma-project/kyma/pull/15969 https://github.com/kyma-project/kyma/pull/15943 https://github.com/kyma-project/kyma/pull/15942

### CODE REVIEW

**Review by muralov — APPROVED** [review]
👍🏼

**Review by mfaizanse — APPROVED** [review]

**Pull request merged**
