### PR TITLE
Trace logging in upgrade tests

### PR DESCRIPTION
**Pull request by friedrichwilken**
This adds some extra trace logging to the upgrade test, since this is one of the points that let's the job break frequently.

```
[DEBUG] fetching trace: bb4bade97471a9b8d68403d7d5748b04 from jaeger
[DEBUG] waiting for trace (id: bb4bade97471a9b8d68403d7d5748b04) from jaeger...
[DEBUG] expected spans:
[DEBUG]   -> istio-ingressgateway.istio-system
[DEBUG]    └> lastorder-qsj77.test-evnt
[DEBUG]     └> eventing-publisher-proxy.kyma-system
[DEBUG]      └> eventing-controller.kyma-system
[DEBUG]       └> lastorder-qsj77.test-evnt
[DEBUG] actual spans:
[DEBUG]   -> istio-ingressgateway.istio-system
[DEBUG]    └> lastorder-qsj77.test-evnt
[DEBUG]     └> lastorder-qsj77.test-evnt
[DEBUG]      └> lastorder-qsj77.test-evnt
[DEBUG]       └> eventing-publisher-proxy.kyma-system
[DEBUG]        └> eventing-controller.kyma-system
[DEBUG]         └> lastorder-qsj77.test-evnt
[DEBUG]          └> lastorder-qsj77.test-evnt
[DEBUG]     └> lastorder-qsj77.test-evnt
[DEBUG] trying to match expected and actual
[DEBUG]   -> istio-ingressgateway.istio-system
[DEBUG]    └> lastorder-qsj77.test-evnt
[DEBUG]     └> lastorder-qsj77.test-evnt [expected eventing-publisher-proxy.kyma-system, continue to search]
[DEBUG]      └> lastorder-qsj77.test-evnt [expected eventing-publisher-proxy.kyma-system, continue to search]
[DEBUG]       └> eventing-publisher-proxy.kyma-system
[DEBUG]        └> eventing-controller.kyma-system
[DEBUG]         └> lastorder-qsj77.test-evnt
      ✓ In-cluster event should have correct tracing spans (10672ms
```

### CODE REVIEW

**Comment by pbochynski** [comment]
Please use draft PRs for work i  progress.

**Review by pbochynski — DISMISSED** [review]

**Review by k15r — APPROVED** [review]

**Review by pbochynski — APPROVED** [review]

**Comment by friedrichwilken** [comment]
/test pre-main-kyma-integration-k3d
--


<br class="Apple-interchange-newline">

**Pull request merged**
