### PR TITLE
Replace satori/go.uuid with google/uuid in Application Registry (#11623)

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

* Replace satori/go.uuid with google/uuid

* Bump image version

**Related issue(s)**

### CODE REVIEW

**Comment by Maladie** [comment]
Duplicate of https://github.com/kyma-project/kyma/pull/11758

**Comment by rafalpotempa** [comment]
Fixed in https://github.com/kyma-project/kyma/pull/11772

**Pull request closed without merging**
