### PR TITLE
Straiten CBS integration tests and wait for Dex availability

### PR DESCRIPTION
**Pull request by parostatkiem**
**Description**

Changes proposed in this pull request:

- Remove `k8s` domain (k8s-client-go is tested by Kubernetes)
- Remove `Rafter` domain (its API is tested in another place)
- Check Dex availability before each test group

**Related issue(s)**

### CODE REVIEW

**Comment by parostatkiem** [comment]
/test all

Everything is green, I just want to make sure it will be like this forever 🌫️

**Comment by parostatkiem** [comment]
/test pre-master-kyma-gke-compass-integration
--

**Review by akucharska — APPROVED** [review]
LGTM

Would be nice to run jobs few more time

**Pull request merged**
