### PR TITLE
Update kyma installer to 1.20.0-rc1

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- installer image updated to 1.20.0-rc1
- removed duplicate key from `installer.yaml` and `installer-local.yaml` (the same PR to master - https://github.com/kyma-project/kyma/pull/10696)
- ...

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/10603

### CODE REVIEW

**Review by Demonsthere — APPROVED** [review]
/meow

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
