### PR TITLE
Do not run knative tests

### PR DESCRIPTION
**Pull request by sjanota**
**Description**

Changes proposed in this pull request:

- Comment out serving acceptance tests as they are causing problems with eventing

**Related issue(s)**

Issue: #2363

### CODE REVIEW

**Comment by Disper** [comment]
Are those comments temporary?
Will there be any follow-up on that?

**Comment by sjanota** [comment]
Yep, they are low cost solution to unblock eventing integration. Follow up is here: https://github.com/kyma-project/kyma/issues/2372

**Comment by Demonsthere** [comment]
Please ass the followup to the related issues :)

**Pull request merged**
