### PR TITLE
Remove Application Broker

### PR DESCRIPTION
**Pull request by janmedrek**
**Description**

Changes proposed in this pull request:

- Remove Application Broker chart
- Remove Application broker sources

**Related issue(s)**

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by majakurcius — APPROVED** [review]

**Review by szwedm — APPROVED** [review]
/lgtm

**Comment by wozniakjan** [comment]
hey @janmedrek, I am trying to spin up kyma without SVCAT from https://github.com/kyma-project/kyma/pull/13675 (which I just rebased on latest master and it should contain https://github.com/kyma-project/kyma/pull/14530 ) but it looks like application connector component is still getting installed by reconciler
```
COMPONENT               CORRELATION_ID                                                               SCHEDULING_ID                                                                PRIORITY   STATE         CREATED AT            UPDATED               REASON                                                                                 
CRDs                    31ba76b0-5521-42ce-a887-d8eb70f0960a--55e518f3-e810-4efa-99b2-367b27c9b96b   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   1          done          2022/06/17 06:57:14   2022/06/17 06:57:46                                                                                          
serverless              31ba76b0-5521-42ce-a887-d8eb70f0960a--669dfa8a-8315-4dd5-96f4-794b1bd26956   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          failed        2022/06/17 06:57:14   2022/06/17 07:05:41   no matches for kind "UsageKind" in version "servicecatalog.kyma-project.io/v1alpha1"   
eventing                31ba76b0-5521-42ce-a887-d8eb70f0960a--cd7a9901-69c7-4300-934b-ae5429c7fede   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 07:00:15                                                                                          
ory                     31ba76b0-5521-42ce-a887-d8eb70f0960a--a526fe8c-0aae-4b11-9da2-adb1cb5e52d7   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 07:00:16                                                                                          
connectivity-proxy      31ba76b0-5521-42ce-a887-d8eb70f0960a--76b0823f-1d0a-48f8-b795-eace30d6f212   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:58:44                                                                                          
certificates            31ba76b0-5521-42ce-a887-d8eb70f0960a--8228a1e1-bcac-4c90-a615-a543cb2ee646   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   2          done          2022/06/17 06:57:14   2022/06/17 06:58:14                                                                                          
cluster-essentials      31ba76b0-5521-42ce-a887-d8eb70f0960a--aa5f3c94-c65d-48f0-8a1c-d5c68525dbff   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   2          done          2022/06/17 06:57:14   2022/06/17 06:58:30                                                                                          
istio                   31ba76b0-5521-42ce-a887-d8eb70f0960a--d7a0544e-85c4-4bcf-a8a6-d4e0ae1ebe95   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   2          done          2022/06/17 06:57:14   2022/06/17 06:58:37                                                                                          
rma                     31ba76b0-5521-42ce-a887-d8eb70f0960a--7dd67a0f-07fc-412f-9989-0a9aa4e97167   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:59:15                                                                                          
application-connector   31ba76b0-5521-42ce-a887-d8eb70f0960a--f4e7a7a9-938a-4829-8f19-0e0880ff1185   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          in_progress   2022/06/17 06:57:14   2022/06/17 07:05:44                                                                                          
monitoring              31ba76b0-5521-42ce-a887-d8eb70f0960a--e1b6d5ef-5de6-47f5-9bf5-28e4b6bc2278   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:59:55                                                                                          
api-gateway             31ba76b0-5521-42ce-a887-d8eb70f0960a--d51f70d9-75a4-4942-b4f7-a6f20d9d23b2   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:58:59                                                                                          
compass-runtime-agent   31ba76b0-5521-42ce-a887-d8eb70f0960a--4b273d14-0374-4488-88e9-2e4b0606332d   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:59:15                                                                                          
logging                 31ba76b0-5521-42ce-a887-d8eb70f0960a--89c5df62-d61b-4476-b9de-dd5392f92ad0   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 07:00:30                                                                                          
istio-resources         31ba76b0-5521-42ce-a887-d8eb70f0960a--dccf7fac-cbbd-493c-b9c2-547f0444b23a   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:58:45                                                                                          
cluster-users           31ba76b0-5521-42ce-a887-d8eb70f0960a--dd7f8e80-a14a-4099-943e-08a36db8c7d3   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:58:45                                                                                          
rafter                  31ba76b0-5521-42ce-a887-d8eb70f0960a--79705d20-c301-4056-a39c-14e91fa4d6ff   31ba76b0-5521-42ce-a887-d8eb70f0960a--1aa0276a-dfb7-478a-a0e9-1f5ce4ce890f   3          done          2022/06/17 06:57:14   2022/06/17 06:59:31                                                                                          
```

eventually, it fails with context deadline exceeded and inside of the SKR there are two crashlooping pods
```
$ k get po
NAME                                  READY   STATUS             RESTARTS        AGE
application-broker-77df69c555-qb74g   1/2     CrashLoopBackOff   9 (3m45s ago)   17m
application-operator-0                0/1     CrashLoopBackOff   8 (85s ago)     17m
```
failing with looking up svcat resources
```
time="2022-06-17T07:12:45Z" level=fatal msg="while listing service classes: the server could not find the requested resource (get serviceclasses.servicecatalog.k8s.io)"
```

**Comment by wozniakjan** [comment]
update, restarting reconciler resolved the mysterious application broker, it had the chart cached

remaining just the application-operator
```
kyma-integration   application-operator-0                                        0/1     CrashLoopBackOff   6 (5m6s ago)   10m
```

which still currently blocks successful kyma provisioning
```
COMPONENT               CORRELATION_ID                                                               SCHEDULING_ID                                                                PRIORITY   STATE   CREATED AT            UPDATED               REASON                                                  
...
application-connector   acd1065b-c97c-4c8d-a0f4-12e09cdb7549--3ecae52f-ca47-4cc2-8cd3-d51d277b29b6   acd1065b-c97c-4c8d-a0f4-12e09cdb7549--58cf435d-2bd2-42db-bd56-6697cb979f4f   3          error   2022/06/17 08:13:48   2022/06/17 08:25:47   context deadline exceeded                                
...
```

**Pull request merged**
