### PR TITLE
Add duration to minikube installation

### PR DESCRIPTION
**Pull request by sayanh**
**Description**

Changes proposed in this pull request:

- Add duration to the minikube installation as we need to monitor the time taken to install Kyma using Minikube. This will in turn will help in choosing the tool which takes the least possible time to install.

**Related issue(s)**

Related https://github.com/kyma-project/kyma/issues/8756

### CODE REVIEW

**Comment by a-thaler** [comment]
I know it is not in scope as first we need to migrate it to use the CLI, still want to mention it here. What about adding the duration to the CLI install command, then it will be usable in all jobs using the CLI? :)

**Comment by sayanh** [comment]
> I know it is not in scope as first we need to migrate it to use the CLI, still want to mention it here. What about adding the duration to the CLI install command, then it will be usable in all jobs using the CLI? :)

@a-thaler Sure, this sounds good. Let's work on that in [this issue](https://github.com/kyma-project/cli/issues/490).

**Pull request merged**
