### PR TITLE
Add security context rules to rafter gateway migrator job

### PR DESCRIPTION
**Pull request by tgorgol**
**Description**

Changes proposed in this pull request:

- Adjust minio gateway migrator jobs to be run as non root
- Add security context rules to rafter gateway migrator job, previously, the rules were temporary removed from this file because of a bug

**Related issue(s)**

See https://github.com/kyma-project/kyma/issues/9552

### CODE REVIEW

**Review by pPrecel — CHANGES_REQUESTED** [review]
I got the following logs during tests on the cluster with the flag `allowPrivilegedContainers: false`:
```
Events:
  Type     Reason        Age                 From            Message
  ----     ------        ----                ----            -------
  Warning  FailedCreate  97s (x5 over 4m7s)  job-controller  Error creating: pods "rafter-upload-service-migrator-pre-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[1]: Invalid value: "persistentVolumeClaim": persistentVolumeClaim volumes are not allowed to be used]
  ```

Have you any idea? Maybe it's because of the configuration of the cluster or the installation CR (I installed the only rafter enabled from kyma installer. Additionally, I applied necessary CRDs manually)

Those logs were collected using ` kubectl describe job -n kyma-system rafter-upload-service-migrator-pre` and the cluster was provisioned on Azure

**Comment by aerfio** [comment]
@pPrecel after this PR is merged https://github.com/kyma-project/kyma/pull/10255 it should work like intended

**Comment by pPrecel** [comment]
I dug into resources on my cluster and I found that PersistentVolumeClain is still not bound:
```
Events:
  Type    Reason                Age                    From                         Message
  ----    ------                ----                   ----                         -------
  Normal  WaitForFirstConsumer  31s (x822 over 3h25m)  persistentvolume-controller  waiting for first consumer to be created before binding
```

**Comment by pPrecel** [comment]
> @pPrecel after this PR is merged #10255 it should work like intended

I tested this PR with changes proposed in your PR and I got still the same error

**Comment by tgorgol** [comment]
Closing as changes were applied in https://github.com/kyma-project/kyma/pull/10258

**Pull request closed without merging**
