### PR TITLE
Rename the backend label in the EPP deployment

### PR DESCRIPTION
**Pull request by VladislavPaskar**
**Description**

rename the label as per [this comment](https://github.com/kyma-project/kyma/issues/13847#issuecomment-1102204187)

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/12606

### CODE REVIEW

**Review by nachtmaar — APPROVED** [review]

**Comment by raypinto** [comment]
From K15r's [comment](https://github.com/kyma-project/kyma/issues/13847#issuecomment-1102204187), I think we need to add the actual backend name (eg. backend:NATS) as well to the label.

**Review by nachtmaar — APPROVED** [review]

**Review by nachtmaar — APPROVED** [review]

**Pull request merged**
