### PR TITLE
Fix Helm Broker port names in services to comply with Istio convention

### PR DESCRIPTION
**Pull request by mjakobczyk**
**Description**

We should follow [official Istio documentation about port naming convention](https://istio.io/latest/docs/reference/config/analysis/ist0118/). After editing both services there is a similar spec which indicates that the used protocol is TCP.

```yaml
...
spec:
  ...
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  ...
```

Changes proposed in this pull request:

- fix port names in `helm-broker-etcd-stateful` service to include protocol prefix
- fix port names in `helm-broker-etcd-stateful-client` service to include protocol prefix
- get rid of the following errors:

```bash
Info [IST0118] (Service helm-broker-etcd-stateful-client.kyma-system) Port name client (port: 2379, targetPort: 2379) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service helm-broker-etcd-stateful-client.kyma-system) Port name metrics (port: 2381, targetPort: 2381) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service helm-broker-etcd-stateful.kyma-system) Port name client (port: 2379, targetPort: 2379) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service helm-broker-etcd-stateful.kyma-system) Port name peer (port: 2380, targetPort: 2380) doesn't follow the naming convention of Istio port.
```

**Related issue(s)**

See: https://github.com/kyma-project/kyma/issues/11686

### CODE REVIEW

**Review by wozniakjan — COMMENTED** [review]
given helm broker is deprecated and will be completely removed from kyma, I would like to propose we don't touch it unless absolutely necessary.

**Comment by strekm** [comment]
@wozniakjan our motivation is to fix all istioctl analyze warnings/infos and to use that in command in pipeline. i wouldn't say this change is harmful or dangerous in any way, more i would say it's cosmetics

**Review by wozniakjan — APPROVED** [review]

**Pull request merged**
