### PR TITLE
Deletion of the dependence to opsfleet in Application Gateway tests

### PR DESCRIPTION
**Pull request by mvshao**
**Description**
We need to delete the dependence to opsfleet, because the project is no longer supported by the author (potential vulnerabilities in future). 

Changes proposed in this pull request:

- deletion of the dependence to opsfleet in Application Gateway tests
- separation Helm Charts of the mock application from test cases

**Related issue(s)**

### CODE REVIEW

**Review by majakurcius — DISMISSED** [review]

**Review by franpog859 — COMMENTED** [review]
We cannot bump the images to the vulnerable ones like `eu.gcr.io/kyma-project/external/golang:1.18.3` 😿

**Review by franpog859 — APPROVED** [review]
LGTM

**Review by majakurcius — APPROVED** [review]

**Pull request merged**
