### PR TITLE
bump istio 1.11.1 -> 1.11.2

### PR DESCRIPTION
**Pull request by piotrkpc**
this PR bumps 1.11.1 to 1.11.2 to address security issues.

### CODE REVIEW

**Review by strekm — CHANGES_REQUESTED** [review]
similar changes should be applied to `istio-configuration` chart

**Review by mjakobczyk — APPROVED** [review]

**Comment by piotrkpc** [comment]
> similar changes should be applied to `istio-configuration` chart

@strekm done, ptal :)

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
