### PR TITLE
Migrate deprecated Istio resources in Application Registry

### PR DESCRIPTION
**Pull request by franpog859**
**Description**

Changes proposed in this pull request:

- Migrate deprecated Istio resources in Application Registry

**Related issue(s)**

See the issue #9094

### CODE REVIEW

**Review by majakurcius — APPROVED** [review]

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by rafalpotempa — COMMENTED** [review]
I've seen it all. 🏅 Looks good, but I need some deeper understanding. :)

**Review by rafalpotempa — APPROVED** [review]

**Comment by franpog859** [comment]
/test pre-master-kyma-gke-upgrade
[previous log](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9356/pre-master-kyma-gke-upgrade/1302860283483525120)

**Pull request merged**
