### PR TITLE
APIRule v1alpha1 removal

### PR DESCRIPTION
**Pull request by strekm**
**Description**

Changes proposed in this pull request:

- APIRule v1alpha1 removal

**Related issue(s)**

- https://github.com/kyma-project/api-gateway/issues/489

### CODE REVIEW

**Comment by barchw** [comment]
Looks like we need to update the configuration in API Gateway controller, as it mounts the certificate as volume: https://github.com/kyma-project/api-gateway/blob/34ad0e736e8b413a5861e75a11e472ec13ba6fe5/main.go#L154C4-L154C4

**Review by triffer — APPROVED** [review]

**Review by chrkl — APPROVED** [review]

**Review by a-thaler — APPROVED** [review]

**Review by muralov — APPROVED** [review]

**Pull request merged**
