### PR TITLE
Fix replicas vs. PDB settings in evaluation profile

### PR DESCRIPTION
**Pull request by ebensom**
**Description**

On clusters with evaluation profile, `istiod`, `istio-ingressgateway` and `cluster-essentials-podpreset-webhook` have PDB configured with `minAvailable: 1` while these workloads are being run with 1 replica only. This blocks pod eviction, which effectively blocks node drain during maintenance activities (such as Gardener K8S cluster upgrades).

Changes proposed in this pull request:

- Have configurable value for `cluster-essentials-podpreset-webhook` PDB `minAvailable` field. Fix disabling the PDB in evaluation profile.
- Disable all Istio PDBs in evaluation profile
- Have at least 2 replicas of istiod in production profile by default, with PDB `minAvailable: 1`

**Related issue(s)**
https://github.tools.sap/kyma/backlog/issues/1564

### CODE REVIEW

**Review by jasiu001 — APPROVED** [review]

**Review by jasiu001 — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by mjakobczyk — APPROVED** [review]

**Pull request merged**
