### PR TITLE
Tests adjusted to fetch shootName by kcp cli

### PR DESCRIPTION
**Pull request by PK85**
**Description**

Changes proposed in this pull request:

- Kyma fast-integration for SKR has new way how shootName is fetched

### CODE REVIEW

**Review by tillknuesting — DISMISSED** [review]

**Review by szwedm — APPROVED** [review]
/lgtm

**Review by szwedm — DISMISSED** [review]
/lgtm

**Review by szwedm — APPROVED** [review]
/lgtm

**Pull request merged**
