### PR TITLE
WIP: Add and correct parameters, removing hardcodes

### PR DESCRIPTION
**Pull request by m-wcislo**
**Description**

- make hardcoded values parametrized, so that they need change in one place
- move existingSecret to globals, to make it work across subcharts
- release wide hardcodes placed in helpers
- container specific values e.g. port ,paths, flags left as it is, not sure if this should be parametrized? 

**Related issue(s)**
Fixes: #4056 

**TODO**
- [ ] investigate why public/private bucket is not recreated after helm delete/install
- [ ] check .sh code for possible templating/parametrization
- [ ] changes in documentation if needed

### CODE REVIEW

**Comment by aerfio** [comment]
@m-wcislo Hi, thanks for contribution! We are in a process of migrating Assetstore and HCMS outside of kyma itself, please have a look at https://github.com/kyma-project/rafter. Your work is actually _really_ relevant right now, because one of the first PRs we have is `Create a Helm Chart for Rafter and its services` - https://github.com/kyma-project/rafter/pull/13 :D Would you like to have a look there?

**Comment by m-wcislo** [comment]
Sorry for late reply, you mean this is duplicate of what is done in https://github.com/kyma-project/rafter/pull/13? The PR is almost done, so not sure if there is any sense to continue this one. What do you think?

**Comment by aerfio** [comment]
@m-wcislo yeah, sorry for late reply too :D Yeah, there's no need to change anything about asset store charts in kyma repo anymore, we are working on its direct successor, Rafter. Have a look there if you are interested, or wait for next Hacktoberfest, we'll surely create issues there with that label 😛

**Comment by m-wcislo** [comment]
Closing then.

**Pull request closed without merging**
