### PR TITLE
Remove Application Broker

### PR DESCRIPTION
**Pull request by akgalwas**
**Description**

Changes proposed in this pull request:

- Remove Application Broker chart
- Remove Application broker sources

### CODE REVIEW

**Review by Maladie — DISMISSED** [review]

**Review by wozniakjan — APPROVED** [review]

**Review by PK85 — CHANGES_REQUESTED** [review]
I will unblock it when decision will be made about including that in 2.2 release

**Comment by wozniakjan** [comment]
hey @PK85 @akgalwas, the kyma 2.4 merge window is open, I think we can rebase this and proceed with the removal. It is currently one of the dependencies of https://github.com/kyma-project/kyma/pull/13675

**Comment by janmedrek** [comment]
Tried playing around with the new GitHub cli and I've broken the history with old forks... Won't risk the force pushes, prepared the new PR with cherry-picked commits from @akgalwas: https://github.com/kyma-project/kyma/pull/14530

**Pull request closed without merging**
