### PR TITLE
Bump k8s-tools on release 1.24

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by NHingerl — APPROVED** [review]

**Review by mmitoraj — APPROVED** [review]

**Review by marcobebway — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by jeremyharisch — APPROVED** [review]

**Review by adamwalach — APPROVED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by dbadura — APPROVED** [review]

**Pull request merged**
