### PR TITLE
Change the tracing override yaml as per new structure is istio-1.5

### PR DESCRIPTION
**Pull request by rakesh-garimella**
**Description**

Changes proposed in this pull request:

- Adjust the override yaml so that that value is applied properly

**Related issue(s)**

### CODE REVIEW

**Review by hisarbalik — DISMISSED** [review]

**Review by alexandra-simeonova — DISMISSED** [review]

**Review by hisarbalik — APPROVED** [review]

**Review by alexandra-simeonova — APPROVED** [review]

**Comment by rakesh-garimella** [comment]
closing this as it needs to be created aginst master branch.

**Pull request closed without merging**
