### PR TITLE
Add 'privileges' security contexts to app-connector

### PR DESCRIPTION
**Pull request by rafalpotempa**
**Description**

Changes proposed in this pull request:

- adds `securityContext.privileged: false` and `securityContext.allowPrivilegeEscalation: false` to application-connector

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/9537

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
This is fine!

**Comment by rafalpotempa** [comment]
\meow

**Review by franpog859 — APPROVED** [review]

**Pull request merged**
