### PR TITLE
add kiali in installer-cr-cluster-compass.yaml

### PR DESCRIPTION
**Pull request by lauraanddola**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by a-thaler** [comment]
The dockerfiles of kiali have security vulnerabilities. We are currently working on re-imaging. Can be merged only after https://github.com/kyma-incubator/third-party-images/pull/16

**Comment by pbochynski** [comment]
@lauraanddola There are merge conflicts. Please rebase your branch on current master.

**Comment by pbochynski** [comment]
Closed due to inactivity.

**Pull request closed without merging**
