### PR TITLE
Use TLS mode SIMPLE in api-server DestinationRule

### LINKED ISSUE #11478: Kyma does not disable mTLS as the documentation and the comment suggest
The quoted destination rule does not disable mTLS for the kubernetes API server as the [documentation](https://kyma-project.io/docs/components/service-mesh#details-istio-setup-in-kyma-kyma-specific-configuration) and the comment of the rule suggest

https://github.com/kyma-project/kyma/blob/53d9ec73d2a7b528554771e6e4aee88715054ae4/resources/istio/files/destination-rules.yaml#L2-L13

A working rule could look like...
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: api-server
  namespace: istio-system 
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
```

### PR DESCRIPTION
**Pull request by oliver-goetz**
**Description**

Changes proposed in this pull request:

- Disable mutual TLS for Kubernetes API Server as [documentation](https://kyma-project.io/docs/components/service-mesh#details-istio-setup-in-kyma-kyma-specific-configuration) suggests
- Use TLS mode SIMPLE instead and validate certificate with cluster internal certification authority

**Related issue(s)**

Resolves #11478

### CODE REVIEW

**Review by mmitoraj — APPROVED** [review]

**Review by cnvergence — APPROVED** [review]

**Comment by Tomasz-Smelcerz-SAP** [comment]
@mmitoraj do not retest please, this does not work. I am investigating.

**Comment by Tomasz-Smelcerz-SAP** [comment]
This PR is not correct. All controllers are failing.
Dex: 
```
i303773@C02FC4VPMD6T Downloads % kubectl -n kyma-system logs dex-8694f9d7fd-lc2ls | tail -n5
{"level":"info","msg":"config skipping approval screen","time":"2021-07-06T13:39:14Z"}
{"level":"info","msg":"config signing keys expire after: 720h0m0s","time":"2021-07-06T13:39:14Z"}
{"level":"info","msg":"config id tokens valid for: 8h0m0s","time":"2021-07-06T13:39:14Z"}
{"level":"info","msg":"failed to list custom resource authcodes.dex.coreos.com, attempting to create: Get \"https://[10.11.240.1]:443/apis/dex.coreos.com/v1/namespaces/kyma-system/authcodes\": http: server gave HTTP response to HTTPS client","time":"2021-07-06T13:39:14Z"}
failed to initialize server: server: failed to list connector objects from storage: failed to list connectors: Get "https://[10.11.240.1]:443/apis/dex.coreos.com/v1/namespaces/kyma-system/connectors": http: server gave HTTP response to HTTPS client
```

Hydra-Maester:
```
i303773@C02FC4VPMD6T Downloads % kubectl -n kyma-system logs ory-hydra-maester-744c896fdc-sjnvh -c hydra-maester | tail -n20 | head
2021-07-06T13:36:17.657Z        ERROR   controller-runtime.manager      Failed to get API Group-Resources       {"error": "Get \"https://10.11.240.1:443/api?timeout=32s\": http: server gave HTTP response to HTTPS client"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/cluster.New
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/cluster/cluster.go:160
sigs.k8s.io/controller-runtime/pkg/manager.New
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/manager.go:278
main.main
        /go/src/github.com/ory/hydra-maester/main.go:77
runtime.main
```

**Review by Tomasz-Smelcerz-SAP — CHANGES_REQUESTED** [review]
This is failing in Prow-provisioned clusters.
Surprisingly, it works when I provision it from your branch... AFAIK Prow performs a rebase with "main" branch before installation. I'll try it out. Can you also double-check if this PR works for you on a custom-provisioned cluster?

**Comment by Tomasz-Smelcerz-SAP** [comment]
@oliver-goetz I have prepared an alternative [PR](https://github.com/kyma-project/kyma/pull/11642) that just removes the questionable DestinationRule.
Such a rule was in Istio Sources up to 1.4.x. In 1.5.x it's installation was conditional, it wasn't installed if "auto-mtls" is used - which was "on" by default. In later Istio versions there's no such DestinationRule at all.
I think it's a legacy object that can be safely deleted, my PR confirms everything works fine.

**Comment by Tomasz-Smelcerz-SAP** [comment]
I am closing this PR in favor of https://github.com/kyma-project/kyma/pull/11642

**Comment by oliver-goetz** [comment]
@Tomasz-Smelcerz-SAP I started this PR because VirtualService pointing to `kubernetes.default.svc.cluster.local` are not working.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes-api
spec:
  hosts:
  - {{ .Values.domain }}
  gateways:
  - kyma-system/kyma-gateway
  http:
  - match:
    - uri:
        prefix: /apis/core.kubernetes/
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 443
        host: kubernetes.default.svc.cluster.local
```

curling this endpoint returns a status 400 `Client sent an HTTP request to an HTTPS server.`

```
curl -v https://xyz.com/apis/core.kubernetes/api
*   Trying ...
* TCP_NODELAY set
* Connected to xyz.com (...) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.xyz.com
*  start date: May 31 20:09:12 2021 GMT
*  expire date: Aug 29 20:09:12 2021 GMT
*  subjectAltName: host "xyz.com" matched cert's "*.xyz.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f899d80d600)
> GET /apis/core.kubernetes/api HTTP/2
> Host: xyz.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 400
< x-envoy-upstream-service-time: 3
< date: Wed, 07 Jul 2021 15:05:51 GMT
< server: istio-envoy
<
Client sent an HTTP request to an HTTPS server.
* Connection #0 to host xyz.com left intact
* Closing connection 0
```

When I add tls mode SIMPLE to the k8s api server destination rule (or create a new one in the namespace of the VirtualService) curl is returning the expected result

```
curl -v https://xyz.com/apis/core.kubernetes/api
*   Trying ...
* TCP_NODELAY set
* Connected to xyz.com (...) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.xyz.com
*  start date: May 31 20:09:12 2021 GMT
*  expire date: Aug 29 20:09:12 2021 GMT
*  subjectAltName: host "xyz.com" matched cert's "*.xyz.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa84100f800)
> GET /apis/core.kubernetes/api HTTP/2
> Host: xyz.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 401
< cache-control: no-cache, private
< content-type: application/json
< date: Wed, 07 Jul 2021 15:05:28 GMT
< content-length: 165
< x-envoy-upstream-service-time: 5
< server: istio-envoy
<
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
* Connection #0 to host xyz.com left intact
}* Closing connection 0
```
I don't think https://github.com/kyma-project/kyma/pull/11642 solves this.

Dex and hydra-maester are crashing on minikube on my machines too. However, on my Gardener clusters both are working with the changed DestinationRule.

I just tried to curl the kubernetes API from within in the Gardener cluster. It is working without the changes in DestinationRule from this PR but returns an error when I activate it.
```
curl -v https://kubernetes.default.svc.cluster.local/api --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
*   Trying 100.64.0.1:443...
* TCP_NODELAY set
* Connected to kubernetes.default.svc.cluster.local (100.64.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

This looks a bit like this common problem: https://istio.io/latest/docs/ops/common-problems/network-issues/#sending-https-to-an-http-port
However, this is related to the istio `ServiceEntry` not to Kubernetes `Service`.

The current state does not allow to use `kubernetes.default.svc.cluster.local` in a VirtualService without creating a dedicated DestinationRule.

**Pull request closed without merging**
