### PR TITLE
move tests/fast-integration/eventing/image to tests/fast-integration/image

### PR DESCRIPTION
**Pull request by FriedrichWilken**
The files in `tests/fast-integration/eventing/image` are not specific to `eventing` but are used for all over `fast-integration` tests so this PR will move the them `tests/fast-integration/image`

### CODE REVIEW

**Comment by VladislavPaskar** [comment]
Totally makes sense to not encapsulate this inside the eventing folder. It can also be a sign for other teams, that it is ready to use by anyone, since it's not only eventing-related.

**Review by VladislavPaskar — APPROVED** [review]
LGTM, Totally makes sense to not encapsulate this inside the eventing folder. It can also be a sign for other teams, that it is ready to use by anyone, since it's not only eventing-related.

**Review by jeremyharisch — APPROVED** [review]

**Pull request merged**
