### PR TITLE
Remove event-bus removal pre-upgrade job

### PR DESCRIPTION
**Pull request by nachtmaar**
**Description**

Changes proposed in this pull request:

- event-bus was removed with this pre-upgrade job in migration to Kyma 1.12. Since event-bus is gone, the script is not required anymore

**Related issue(s)**

### CODE REVIEW

**Comment by sayanh** [comment]
Would it make sense to delete this [job](https://github.com/kyma-project/kyma/blob/master/resources/nats-streaming/templates/migration-jobs.yaml) as well?

**Comment by nachtmaar** [comment]
> Would it make sense to delete this [job](https://github.com/kyma-project/kyma/blob/master/resources/nats-streaming/templates/migration-jobs.yaml) as well?

From what I understand it was only required once to handle the selector updates. See the PR which introduced it: https://github.com/kyma-project/kyma/pull/5176/files
I would like to remove it in another small PR :)

**Comment by sayanh** [comment]
> selector updates

Right, as the selectors are good now, the pre-upgrade hook is irrelevant. 

> I would like to remove it in another small PR :)

Sure, this works.

**Pull request merged**
