### PR TITLE
add global.installCRD to kyma2 values

### PR DESCRIPTION
**Pull request by elchead**
**Description**
needed to remove interecepts in hydroform (https://github.com/kyma-project/hydroform/pull/290)
Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
https://github.com/kyma-project/cli/issues/892

### CODE REVIEW

**Review by clebs — APPROVED** [review]

**Review by mjakobczyk — APPROVED** [review]

**Comment by elchead** [comment]
retest

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
