### PR TITLE
Upgrade prometheus operator and prometheus-istio

### PR DESCRIPTION
**Pull request by lindnerby**
**Description**

Following Kyma customizations were reverted to be compatible with the upstream chart:
1. Revert label customization, stick to upstream labels
2. Remove Alertmanager from the service mesh
3. Remove custom Alertmanager template
4. Unify Grafana auth proxy labels to prevent it to be incorrectly selected by the upstream service monitor.

Following changes were carried over from the upstream chart:
1. Rename service pod - stick to [Istio port naming convention](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)
2.  New alertrules:
- AlertmanagerFailedToSendAlerts
- AlertmanagerClusterFailedToSendAlerts
- AlertmanagerClusterFailedToSendAlerts Warning
- AlertmanagerClusterDown
- AlertmanagerClusterCrashlooping
- ConfigReloaderSidecarErrors
- KubeStateMetricsShardingMismatch
- KubeStateMetricsShardsMissing
- KubeAPITerminatedRequests
- NodeFileDescriptorLimit
- PrometheusLabelLimitHit
- PrometheusTargetSyncFailure
- PrometheusOperatorSyncFailed
3. Rename alertrules:
- AggregatedAPIDown -> KubeAggregatedAPIDown 
- AggregatedAPIErrors -> KubeAggregatedAPIErrors

Also, `ory-hydra-maester` and `ory-oathkeeper` are now scraped via plain HTTP.

**Related issue(s)**

Fixes https://github.com/kyma-project/kyma/issues/11567

### CODE REVIEW

**Review by chrkl — DISMISSED** [review]

**Review by skhalash — APPROVED** [review]

**Review by chrkl — APPROVED** [review]

**Comment by cnvergence** [comment]
Generally okay with this solution, let's just come back to this scraping issue with Ory later with a new issue, please

**Review by cnvergence — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
