### PR TITLE
Restore Istio PeerAuthentications (with strict mode)

### PR DESCRIPTION
**Pull request by skhalash**
**Description**

Changes proposed in this pull request:

- [This PR](https://github.com/kyma-project/kyma/pull/11994) removes PeerAuthentication resources, which became unneeded after making Prometheus scrape the corresponding targets via HTTPS. However, when testing Kyma 1 to Kyma 2 upgrades using the Reconciler we found out that the TLS-scraped targets are down. The reason for that is the left-over PeerAuthentication resources with permissive mTLS mode set (Reconciler does not remove deleted resources when upgrading Kyma). In order to circumvent this problem, it was decided to restore the PeerAuthentication resources (with strict mode instead of permissive). 

**Related issue(s)**

Fixes https://github.com/kyma-project/kyma/issues/12743

### CODE REVIEW

**Review by k15r — APPROVED** [review]

**Review by chrkl — APPROVED** [review]

**Review by veichtj — APPROVED** [review]

**Review by wozniakjan — APPROVED** [review]
giving blind lgtm, it was explained to me that this is putting istio configuration back that was temporarily disabled.
/lgtm

**Pull request merged**
