### PR TITLE
update docu to use $KYMA_VERSION only

### PR DESCRIPTION
**Pull request by tehret77**
**Description**

Changes proposed in this pull request:

- Fix documentation to use the correct environment variable defined in section "Choose the release to install" step 2

**Related issue(s)**

### CODE REVIEW

**Review by majakurcius — APPROVED** [review]

**Comment by majakurcius** [comment]
HI @tehret77! Thank you for your contribution and spotting that :) Could you please sign the CLA so we can merge the PR? TIA!

**Comment by tehret77** [comment]
Hi @majakurcius, CLA signed now.
Cheers, Torben

**Comment by pbochynski** [comment]
@majakurcius Can you merge the PR?

**Pull request merged**
