### PR TITLE
Increase Istio Gateway security

### PR DESCRIPTION
**Pull request by Demonsthere**
**Description**

Changes proposed in this pull request:

- Change minimal tls version to 1.1
- Change list of accepted ciphers 

**Related issue(s)**

- Fix for #7346

### CODE REVIEW

**Comment by Demonsthere** [comment]
Tests using ssllabs with the new Gateway options: Zrzut ekranu 2020-02-26 o 15 55 25

**Comment by Tomasz-Smelcerz-SAP** [comment]
Verified. It looks we don't support TLS 1.3 at all. 
For comparison this is how it looks BEFORE changes (1.0 is supported): 

Screenshot 2020-02-27 at 13 20 06

**Pull request merged**
