### PR TITLE
Upgrade docker libs in application-connector to version 19.03.13

### PR DESCRIPTION
**Pull request by koala7659**
This should mitigate multiple security vulnerabilities reported by protecode scans.

Components with upgraded docker libs

 * application-operator
* application-operator-tests
* application-registry
* application-gateway
* application-gateway-tests
* application-connectivity-validator
* compass-runtime-agent

### CODE REVIEW

**Comment by koala7659** [comment]
Fisrt 

 `go get github.com/docker/docker@v19.03.13                                
go: github.com/docker/docker v19.03.13 => v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible`

and then 

` github.com/docker/docker => github.com/docker/docker v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible `

**Review by franpog859 — APPROVED** [review]
LGTM

**Pull request merged**
