### PR TITLE
Clean-up default and not-used values of Istio Operator

### LINKED ISSUE #10616: Remove unnecessarily exposed ports from istio-ingressgateway
**Description**

Kyma opens a lot of unneeded ports on `istio-ingressgateway` service. This is not only bad from security perspective, but also makes Kyma installation on OpenStack to take a lot more time as K8S cloud controller manager creates LB listener for each of these ports one by one.

**Expected result**

[Default Istio settings](https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml#L15-L26):

```
    ports:
    - port: 15021
      targetPort: 15021
      name: status-port
      protocol: TCP
    - port: 80
      targetPort: 8080
      name: http2
      protocol: TCP
    - port: 443
      targetPort: 8443
      name: https
      protocol: TCP
```

**Actual result**

[Kyma production profile overrides](https://github.com/kyma-project/kyma/blob/master/resources/istio/files/istio-operator-cluster-production.yaml#L87-L116):
```
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - port: 15012
            targetPort: 15012
            name: tcp-istiod
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          - name: tcp
            port: 31400
            targetPort: 31400
          - name: tls
            port: 15443
            targetPort: 15443
          - port: 15029
            targetPort: 15029
            name: kiali
          - port: 15030
            targetPort: 15030
            name: prometheus
          - port: 15031
            targetPort: 15031
            name: grafana
          - port: 15032
            targetPort: 15032
            name: tracing
```

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by cnvergence**
**Description**

Changes proposed in this pull request:

- Remove unused ports opened and other settings for multicluster Istio
- Align with default Istio profile

**Related issue(s)**

Fixes #10616 #11636

### CODE REVIEW

**Review by piotrkpc — DISMISSED** [review]
/lgtm

**Review by mjakobczyk — APPROVED** [review]

**Review by piotrkpc — APPROVED** [review]

**Pull request merged**
