### PR TITLE
Fix for storing  timestamp of lastAttempt of synchronisation in Connection CR and processing it in reconciliation loop

### PR DESCRIPTION
**Pull request by koala7659**
**Description**
We have a code in Compass Runtime Agent reconciliation loop to wait with next attempt of SKR synchronisation with Compass with the value of `minimalConfigSyncTime` which normally is `30s`. The waiting time window is calculated with using value of previous attempt timestamp stored as  'SynchronizationStatus.LastAttempt' in Compass Connection CR.  (`Current time - timestamp of last attempt`).

The problem was that when saving this timestamp - its value was taken before any communication with Compass API is happened. As a result in a situation when communication with Compass API resulted with timeout after `TimeoutTime` we did not wait enough long before trying to do it again. The fix is to store in Connection CR the value of lastAttempt time read AFTER any API call to Compass fails.

Additionally same safety check to wait before next call to Compass API has been added to the code of Initialisation of  Compass Connection for newly created runtime. As a result in reconciliation loop all attempts subsequent to call CompassAPI will be executed no more oftern than `minimalConfigSyncTime`

**Before:**

```
time := readTimestamp()
executeCompassAPICallWhichFailsAfterTimeoutTime()
saveLastAttemptTimeToCompassCR(time)
```

For the next attempt we wait  `minimalConfigSyncTime` -  `TimeoutTime`

**After:**

```
executeCompassAPICallWhichFailsAfterTimeoutTime()
saveLastAttemptTimeToCompassCR(readTimestamp())
```

For the next attempt we wait  `minimalConfigSyncTime` no matter how long the `TimeoutTime` was

**Example logs from one runtime where you can observe the problem.**
Calls are waiting 6-7 secs not 30 sec.

```
2021-11-22 06:58:43	
{"log":"time=\"2021-11-22T05:58:43Z\" level=error msg=\"Error while trying to maintain connection: Failed to connect to Compass Connector: Management info is empty\" CompassConnection=compass-connection Supervisor=CompassConnection
","time":"2021-11-22T05:58:43.744997887Z"}
2021-11-22 06:58:50	
{"log":"time=\"2021-11-22T05:58:50Z\" level=error msg=\"Error while trying to maintain connection: Failed to connect to Compass Connector: Management info is empty\" CompassConnection=compass-connection Supervisor=CompassConnection
","time":"2021-11-22T05:58:50.984370156Z"}
2021-11-22 06:58:59	
{"log":"time=\"2021-11-22T05:58:59Z\" level=error msg=\"Error while trying to maintain connection: Failed to connect to Compass Connector: Management info is empty\" CompassConnection=compass-connection Supervisor=CompassConnection
","time":"2021-11-22T05:58:59.159868934Z"}
2021-11-22 06:59:07	
{"log":"time=\"2021-11-22T05:59:07Z\" level=error msg=\"Error while trying to maintain connection: Failed to connect to Compass Connector: Management info is empty\" CompassConnection=compass-connection Supervisor=CompassConnection
","time":"2021-11-22T05:59:07.17789839Z"}
```

### CODE REVIEW

**Comment by koala7659** [comment]
Sample logs: simulated fail of certificates reneval after 10 s timeout. One minute of waiting period:

```
Simulated call to compass failed:
time="2021-11-24T16:57:38Z" level=info msg="Processing Compass Connection, current status: ConnectionMaintenanceFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-24T16:57:38Z" level=info msg="Trying to connect to Compass and apply Runtime configuration..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-24T16:57:38Z" level=info msg="Trying to maintain connection to Connector with https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/connector/graphql url..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:57:38Z" level=info msg="Trying to maintain certificates connection... Renewal: false" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:57:48Z" level=error msg="Error while trying to maintain connection: Test Error - Timeout connection!!!" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:57:48Z" level=info msg="Setting Compass Connection to ConnectionMaintenanceFailed state" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:57:48Z" level=info msg="Synchronization finished. Compass Connection status: ConnectionMaintenanceFailed" CompassConnection=compass-connection Controller=CompassConnection

1. Immediate repeat is skipped after 0s. Next attempt should be allowed after 16:58:48
time="2021-11-24T16:57:48Z" level=info msg="Processing Compass Connection, current status: ConnectionMaintenanceFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-24T16:57:48Z" level=info msg="Skipping connection initialization. Minimal config resync time not passed. Last attempt: 2021-11-24 16:57:48 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

2 Attempt after 50s is skipped.   Next attempt should be allowed after 16:58:48
time="2021-11-24T16:58:39Z" level=info msg="Processing Compass Connection, current status: ConnectionMaintenanceFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-24T16:58:39Z" level=info msg="Skipping connection initialization. Minimal config resync time not passed. Last attempt: 2021-11-24 16:57:48 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

3 Attempt is successful. We are  after 16:58:48. Simulated call to compass fails again:
time="2021-11-24T16:59:09Z" level=info msg="Processing Compass Connection, current status: ConnectionMaintenanceFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-24T16:59:09Z" level=info msg="Trying to connect to Compass and apply Runtime configuration..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-24T16:59:09Z" level=info msg="Trying to maintain connection to Connector with https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/connector/graphql url..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:59:09Z" level=info msg="Trying to maintain certificates connection... Renewal: false" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:59:19Z" level=error msg="Error while trying to maintain connection: Test Error - Timeout connection!!!" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:59:19Z" level=info msg="Setting Compass Connection to ConnectionMaintenanceFailed state" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-24T16:59:20Z" level=info msg="Synchronization finished. Compass Connection status: ConnectionMaintenanceFailed" CompassConnection=compass-connection Controller=CompassConnection
```

**Comment by koala7659** [comment]
Sample logs: simulated fail of initialisation of connection after delete with 10s Compass timeout. `minimalConfigSyncTime` is one minute:

```
Simulated call to compass failed:
time="2021-11-25T12:07:47Z" level=info msg="Compass Connection deleted. Trying to initialize new connection..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:07:57Z" level=error msg="Error while establishing connection with Compass: Timeout!!!!" Supervisor=CompassConnection
time="2021-11-25T12:07:57Z" level=info msg="Setting Compass Connection to ConnectionFailed state" Supervisor=CompassConnection
time="2021-11-25T12:07:57Z" level=info msg="Attempt to initialize Compass Connection ended with status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection

1. Immediate repeat is skipped after 0s. Next attempt should be allowed after 12:08:57

time="2021-11-25T12:07:57Z" level=info msg="Processing Compass Connection, current status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:07:57Z" level=info msg="Skipping connection initialization. Minimal Compass Conenction initialisation time interval not passed. Last attempt: 2021-11-25 12:07:57 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

2 Attempt at 12:08:54 is skipped.   Next attempt should be allowed after 12:08:57

time="2021-11-25T12:08:54Z" level=info msg="Processing Compass Connection, current status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:08:54Z" level=info msg="Skipping connection initialization. Minimal Compass Conenction initialisation time interval not passed. Last attempt: 2021-11-25 12:07:57 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

3 Attempt at 12:09:55 is accepted.

time="2021-11-25T12:09:55Z" level=info msg="Processing Compass Connection, current status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:09:55Z" level=info msg="Attempting to initialize connection with Compass..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:09:55Z" level=info msg="Compass Connection exists with state ConnectionFailed" Supervisor=CompassConnection
time="2021-11-25T12:10:05Z" level=error msg="Error while establishing connection with Compass: Timeout!!!!" Supervisor=CompassConnection
time="2021-11-25T12:10:05Z" level=info msg="Setting Compass Connection to ConnectionFailed state" Supervisor=CompassConnection
time="2021-11-25T12:10:05Z" level=info msg="Attempt to initialize Compass Connection ended with status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
```

**Comment by koala7659** [comment]
Real fail of initialisation of connection with Director. `minimalConfigSyncTime` is one minute:

```
time="2021-11-25T12:45:16Z" level=info msg="Processing Compass Connection, current status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:45:16Z" level=info msg="Attempting to initialize connection with Compass..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:45:16Z" level=info msg="Compass Connection exists with state ConnectionFailed" Supervisor=CompassConnection
time="2021-11-25T12:45:16Z" level=error msg="Error while establishing connection with Compass: Failed to fetch configuration: Failed to get configuration: graphql: server returned a non-200 status code: 400" Supervisor=CompassConnection
time="2021-11-25T12:45:16Z" level=info msg="Setting Compass Connection to ConnectionFailed state" Supervisor=CompassConnection
time="2021-11-25T12:45:16Z" level=info msg="Attempt to initialize Compass Connection ended with status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection

1. Immediate repeat is skipped after 0s. Next attempt should be allowed after 12:46:16

time="2021-11-25T12:45:16Z" level=info msg="Processing Compass Connection, current status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:45:16Z" level=info msg="Skipping connection initialization. Minimal Compass Conenction initialisation time interval not passed. Last attempt: 2021-11-25 12:45:16 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

2. Attempt at 12:46:17 is accepted.

time="2021-11-25T12:46:17Z" level=info msg="Processing Compass Connection, current status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:46:17Z" level=info msg="Attempting to initialize connection with Compass..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T12:46:17Z" level=info msg="Compass Connection exists with state ConnectionFailed" Supervisor=CompassConnection
time="2021-11-25T12:46:17Z" level=error msg="Error while establishing connection with Compass: Failed to fetch configuration: Failed to get configuration: graphql: server returned a non-200 status code: 400" Supervisor=CompassConnection
time="2021-11-25T12:46:17Z" level=info msg="Setting Compass Connection to ConnectionFailed state" Supervisor=CompassConnection
time="2021-11-25T12:46:17Z" level=info msg="Attempt to initialize Compass Connection ended with status: ConnectionFailed" CompassConnection=compass-connection Controller=CompassConnectio
```

**Comment by koala7659** [comment]
Simulated fail of initialisation of connection problem with Director timeout 10 secons. `minimalConfigSyncTime` is one minute:

```
Simulated  call to compass Director failed:
time="2021-11-25T15:35:51Z" level=info msg="Trying to maintain certificates connection... Renewal: false" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:35:51Z" level=info msg="Connection maintained. Director URL: https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/director/graphql , ConnectorURL: https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/connector/graphql" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:35:51Z" level=info msg="Reading configuration required to fetch Runtime configuration..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:35:51Z" level=info msg="Fetching configuration from Director, from https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/director/graphql url..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:36:01Z" level=error msg="Test Error - Director connection timeout!!!" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:36:01Z" level=info msg="Setting Compass Connection to SynchronizationFailed state" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:36:01Z" level=info msg="Synchronization finished. Compass Connection status: SynchronizationFailed" CompassConnection=compass-connection Controller=CompassConnection

1. Immediate repeat is skipped after 0s. Next attempt should be allowed after15:37:01

time="2021-11-25T15:36:01Z" level=info msg="Processing Compass Connection, current status: SynchronizationFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T15:36:01Z" level=info msg="Skipping connection initialization. Minimal Compass Conenction initialisation time interval not passed. Last attempt: 2021-11-25 15:35:51 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

2. Second attempt skipped.  Next attempt should be allowed after 15:37:01

time="2021-11-25T15:36:52Z" level=info msg="Processing Compass Connection, current status: SynchronizationFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T15:36:52Z" level=info msg="Skipping config initialization/synchronization. Minimal Compass Conenction resync time interval not passed. Last attempt: 2021-11-25 15:36:01 +0000 UTC" CompassConnection=compass-connection Controller=CompassConnection

Attemt success 

time="2021-11-25T15:37:23Z" level=info msg="Processing Compass Connection, current status: SynchronizationFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T15:37:23Z" level=info msg="Trying to connect to Compass and apply Runtime configuration..." CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T15:37:23Z" level=info msg="Trying to maintain connection to Connector with https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/connector/graphql url..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:23Z" level=info msg="Trying to maintain certificates connection... Renewal: false" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:23Z" level=info msg="Connection maintained. Director URL: https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/director/graphql , ConnectorURL: https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/connector/graphql" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:23Z" level=info msg="Reading configuration required to fetch Runtime configuration..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:23Z" level=info msg="Fetching configuration from Director, from https://compass-gateway-mtls.mps.dev.kyma.cloud.sap/director/graphql url..." CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:33Z" level=error msg="Test Error - Director connection timeout!!!" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:33Z" level=info msg="Setting Compass Connection to SynchronizationFailed state" CompassConnection=compass-connection Supervisor=CompassConnection
time="2021-11-25T15:37:33Z" level=info msg="Synchronization finished. Compass Connection status: SynchronizationFailed" CompassConnection=compass-connection Controller=CompassConnection
time="2021-11-25T15:37:33Z" level=info msg="Processing Compass Connection, current status: SynchronizationFailed" CompassConnection=compass-connection Controller=CompassConnection
```

**Review by Maladie — APPROVED** [review]

**Pull request merged**
