### PR TITLE
Pod preset cleanup

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

`PodPreset` has been [deprecated in Kyma 2.4](https://kyma-project.io/blog/2022/6/30/release-notes-24#pod-preset-deprecation-note). This PR intends to clear residual content in Kyma related to pod presets.

**Related issue(s)**

closes: https://github.com/kyma-project/kyma/issues/16656

### CODE REVIEW

**Comment by wozniakjan** [comment]
@PK85 the changes to evaluation and production profiles in https://github.com/kyma-project/kyma/pull/16647/commits/9a2327c1ac7c3dcad79ea29f3e6230ea18f147a6 to get rid of `PodPreset` make them not very useful, any candidates for helm chart values to pass provide here instead?

**Comment by wozniakjan** [comment]
> @wozniakjan please make sure this PR is not merged before checking production environment that we have no single use of that controller.

there are currently 42 SKRs in stage and 80 SKRs in prod that have `PodPreset` resources

**Comment by wozniakjan** [comment]
failing `pre-main-kyma-gardener-azure-alpha-eval` 

```
2023-01-24T10:46:42.227Z	ERROR	clusteressentials/action.go:31	Error while fetching existing mutatingWebhookConfigurations [mutatingwebhookconfigurations.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" not found]..
```

removing `PodPreset` content from reconciler and reconciler tests in: https://github.com/kyma-incubator/reconciler/pull/1286

**Comment by wozniakjan** [comment]
/unhold
green light from @PK85

**Review by jaroslaw-pieszka — APPROVED** [review]

**Review by pbochynski — APPROVED** [review]

**Review by IwonaLanger — APPROVED** [review]

**Review by cnvergence — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Review by k15r — APPROVED** [review]

**Pull request merged**
