### PR TITLE
minor fixes to eventing fi tests

### PR DESCRIPTION
**Pull request by raypinto**
**Description**

Changes proposed in this pull request:

- update apirule crd version to v1beta1
- fix typos
- remove unused functions, variables, function arguments
- update readme

**Related issue(s)**

### CODE REVIEW

**Review by NHingerl — APPROVED** [review]

**Review by mfaizanse — DISMISSED** [review]

**Comment by mfaizanse** [comment]
@raypinto There is some syntax error. Can you fix?

**Comment by raypinto** [comment]
@mfaizanse There were issues from merging master back into my branch. I have fixed it now. Can you please trigger the tests again? Thanks

**Review by mfaizanse — APPROVED** [review]

**Review by NHingerl — APPROVED** [review]

**Pull request merged**
