### PR TITLE
Change insensitive terms into their inclusive alternatives

### LINKED ISSUE #11109: Change "whitelist" and "whitelist" entries in API Gateway
**Description**

- There are some `whitelist` and `blacklist` entries in the API Gateway code that need updating:

- [resources/api-gateway/templates/_helpers.tpl](https://github.com/kyma-project/kyma/blob/main/resources/api-gateway/templates/_helpers.tpl)
 - [resources/api-gateway/templates/deployment.yaml](https://github.com/kyma-project/kyma/blob/main/resources/api-gateway/templates/deployment.yaml)
 - [resources/api-gateway/values.yaml](https://github.com/kyma-project/kyma/blob/main/resources/api-gateway/values.yaml)

- The same applies to the `whitelist` and `blacklist` terms in the [API Gateway repository](https://github.com/kyma-incubator/api-gateway) (code and related descriptions in docs that can be changed only when the code is modified accordingly). See all entries in the repository
- [whitelist phrases](https://github.com/kyma-incubator/api-gateway/search?q=whitelist)
- [blacklist phrases](https://github.com/kyma-incubator/api-gateway/search?q=blacklist)

Please update them into more inclusive terms following this decision tree:

image

**Reasons**

Changing insensitive terms into their inclusive alternatives.

These changes need to be done by the dev team responsible for the API Gateway component (Goats).
It has already been discussed with @colunira.

**Attachments**

This change is related to the main [issue #515](https://github.com/kyma-project/community/issues/515).

### PR DESCRIPTION
**Pull request by cnvergence**
**Related issue(s)**

Fixes #11109

### CODE REVIEW

**Review by piotrkpc — COMMENTED** [review]
/lgtm

**Review by mjakobczyk — DISMISSED** [review]

**Review by mjakobczyk — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
