### PR TITLE
Remove moved code

### PR DESCRIPTION
**Pull request by VOID404**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

https://github.com/kyma-project/application-connector-manager/issues/267

### CODE REVIEW

**Review by m00g3n — DISMISSED** [review]
LGTM

**Review by grego952 — APPROVED** [review]

**Comment by a-thaler** [comment]
As you are the last one in the folders, could you please directly remove these folder:
- resources
- components
- tests
- installation

Thanks a lot

**Review by a-thaler — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Review by m00g3n — APPROVED** [review]
LGTM

**Review by jeremyharisch — APPROVED** [review]

**Review by Disper — APPROVED** [review]
re-approving

**Pull request merged**
