### PR TITLE
Add autoscaling to Application Gateway

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

- Application Operator will now deploy Horizontal Pod Autoscaler to control number of Application Gateway replicas 

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/9587

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
Top class horizontal pod autoscaler example.

**Review by koala7659 — APPROVED** [review]

**Review by koala7659 — APPROVED** [review]
OK

**Review by franpog859 — APPROVED** [review]
Superb

**Pull request merged**
