### PR TITLE
remove knative based components

### PR DESCRIPTION
**Pull request by k15r**
**Description**

Changes proposed in this pull request:

- remove unnecessary components that have been used in kyma < 1.21

**Notes**
knative crds are still required in the post upgrade hook. as soon as the eventing post upgrade hook has been removed we will also remove all knative related crds

addidtional changes to the application-broker will be implemented in this pr: https://github.com/kyma-project/kyma/pull/10924
**Related issue(s)**

### CODE REVIEW

**Review by alexandra-simeonova — APPROVED** [review]

**Review by majakurcius — DISMISSED** [review]

**Review by colunira — DISMISSED** [review]
/meow

**Review by marcobebway — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by a-thaler — APPROVED** [review]

**Review by pPrecel — APPROVED** [review]
/meow

**Review by colunira — APPROVED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by crabtree — APPROVED** [review]

**Review by dariadomagala — APPROVED** [review]

**Pull request merged**
