### PR TITLE
Extending Compass Runtime Agent with a job to perform runtime synchronisation with compass after release upgrade

### PR DESCRIPTION
**Pull request by koala7659**

### CODE REVIEW

**Comment by koala7659** [comment]
Question for reviewer: Does this job need a security context to be set?

For example:

```
      securityContext:
        runAsUser: 2000
```

**Review by akgalwas — APPROVED** [review]

**Comment by rafalpotempa** [comment]
Regarding Privileged Containers in https://github.com/kyma-project/kyma/pull/9790 it would require some adjustments. 
I think the best strategy would be to merge `this` PR and add PSP on https://github.com/kyma-project/kyma/pull/9790.

**Pull request merged**
