### PR TITLE
Fix function reconcile datarace with configmaps controller

### PR DESCRIPTION
**Pull request by aerfio**
**Description**

Changes proposed in this pull request:

- added needed fix and proper comment for posterity
- datarace is explained in that comment

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/10001

### CODE REVIEW

**Review by dbadura — DISMISSED** [review]

**Comment by aerfio** [comment]
After waiting a couple of seconds after starting controller I've not observed this behaviour, so I'll close this for now without merging

**Pull request closed without merging**
