### PR TITLE
Kyma release 1.17.0-rc3

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- installer bumped to 1.17.0-rc3
- remove `role-collections` parameter for ServiceInstance in `uaa-activator` component
- ...

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9833

### CODE REVIEW

**Review by jasiu001 — DISMISSED** [review]

**Comment by adamwalach** [comment]
Uaa-activator component job: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9977/pre-kyma-components-uaa-activator/1329154411246653440
Re-taged to eu.gcr.io/kyma-project/uaa-activator:release-1.17-9977

**Review by jasiu001 — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
