### PR TITLE
Bump image tag for monitoring to ignore test pods during testing.

### PR DESCRIPTION
**Pull request by rakesh-garimella**
**Description**

Changes proposed in this pull request:

- Due to istio-1.15 we are having targets pointing to the test pods. We should skip them since they would be deleted after the test is finished

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/9393

### CODE REVIEW

**Review by hisarbalik — APPROVED** [review]

**Comment by rakesh-garimella** [comment]
Related to istio upgrade here: https://github.com/kyma-project/kyma/pull/8898

**Comment by rakesh-garimella** [comment]
The image bump was made directly into the istio PR (https://github.com/kyma-project/kyma/pull/8898) so closing this ine.

**Pull request closed without merging**
