### PR TITLE
Change ARK references to Velero

### PR DESCRIPTION
**Pull request by sayanh**
**Description**

Changes proposed in this pull request:

- Change ARK references Velero
- Fixed prometheus, function, statefulset test for mTLS
- Commented out other tests for now which will be solved [here](https://github.com/kyma-project/kyma/issues/4157)

Further changes can be done through these tickets:
- https://github.com/kyma-project/kyma/issues/4166
- https://github.com/kyma-project/kyma/issues/4164

### CODE REVIEW

**Comment by sayanh** [comment]
Passed tests in backup/restore test suite with velero:

- [ ] myFunctionTest

- [ ] myStatefulSetTest

- [ ] myDeploymentTest

- [ ] myPrometheusTest

- [ ] appBrokerTest

- [ ] helmBrokerTest

- [ ] scAddonsTest

- [ ] myNamespaceControllerTest

- [ ] apiControllerTest

- [ ] myGrafanaTest

- [ ] myMicroFrontendTest

- [ ] myAssetStoreTest

- [ ] myCmsTest

**Comment by a-thaler** [comment]
The velero-plugins project is a regular component which will be part of any kyma production system, I don't see a reason why it is in a "tools" folder. I would like to see that you address it as you touch it already, see also https://github.com/kyma-project/kyma/issues/2502 but it is not in the scope of this story... so I will approve it anyway

**Pull request merged**
