### PR TITLE
Adapt application connectivity tests for new eventing

### PR DESCRIPTION
**Pull request by sayanh**
**Description**

Changes proposed in this pull request:

- Adapt application connectivity tests for new eventing
The chart changes are in PR https://github.com/kyma-project/kyma/pull/10793 where application-connectivity tests are passing in the gke-integration jobs.

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
It is OK!

**Review by franpog859 — APPROVED** [review]

**Review by franpog859 — COMMENTED** [review]
You may want to bump the images for Application Operator and it's tests

**Review by franpog859 — COMMENTED** [review]
Could you also remove the parameters from the charts?

**Comment by sayanh** [comment]
@franpog859 The chart changes are [here](https://github.com/kyma-project/kyma/pull/10793/files#diff-8c0cc14de9298a57193cd34b130a02275d8213e14e66a003e634df90a23e5175).

**Pull request merged**
