### PR TITLE
cleanup monitoring leftovers

### PR DESCRIPTION
**Pull request by a-thaler**
**Description**

Cleanup of monitoring resources

Changes proposed in this pull request:

- With https://github.com/kyma-project/kyma/pull/9486 new dashboards got introduced but old one were not deleted
- With https://github.com/kyma-project/kyma/pull/8978/files the AKS fix got removed, no the cleanup job of the fix can be removed
- With https://github.com/kyma-project/kyma/pull/9486 the old alert rules needs to get removed which was missed in the PR

**Related issue(s)**

### CODE REVIEW

**Review by suleymanakbas91 — APPROVED** [review]

**Review by suleymanakbas91 — CHANGES_REQUESTED** [review]
Could you please delete the alert rules as well?

**Comment by a-thaler** [comment]
Good point, deleted them as well

**Review by suleymanakbas91 — APPROVED** [review]

**Pull request merged**
