### PR TITLE
Upgrade Prometheus

### PR DESCRIPTION
**Pull request by rakesh-garimella**
**Description**
Upgrade Prometheus to latest

**Related issue(s)**

Fixes: #3071

### CODE REVIEW

**Comment by venturasr** [comment]
Apart from Sayan's found in `kyma/resources/monitoring/charts/prometheus/templates/servicemonitors.yaml`, I have approved the PR as I think this should be an small change to be included in this PR. And the upgraded of prometheus works.

Back to Sayan comment, the current version in prometheus operator master has

https://github.com/lancomsystems/prometheus-operator/blob/7488a60df1cd45ea4b256917d3157d2dfad5245d/helm/prometheus/templates/servicemonitors.yaml#L18

`        prometheus: {{ $releaseName }}`

Some other related issues:
https://github.com/coreos/prometheus-operator/issues/1248
https://github.com/coreos/prometheus-operator/issues/1240
https://github.com/coreos/prometheus-operator/pull/1263

**Comment by sayanh** [comment]
Alerts in configmap are missing:
resources/monitoring/charts/alert-rules/templates/alert-rules-configmap.yaml

**Pull request merged**
