### PR TITLE
Remove not needed Application Connector tests

### PR DESCRIPTION
**Pull request by franpog859**
**Description**

Changes proposed in this pull request:

- Remove old Application Connector tests
- The Application Gateway test directories seem to be still needed. They are going to be removed [here, in the Application Operator removal story](https://github.com/kyma-project/kyma/issues/12845), as the Gateway tests are a part of this component itself
- Remove not needed CODEOWNERS lines

**Related issue(s)**

See the [issue here](https://github.com/kyma-project/kyma/issues/13977)

### CODE REVIEW

**Review by majakurcius — DISMISSED** [review]

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by koala7659 — APPROVED** [review]
LGTM again

**Review by majakurcius — APPROVED** [review]

**Review by a-thaler — APPROVED** [review]

**Pull request merged**
