### PR TITLE
Removal of api-gateway and istio components

### PR DESCRIPTION
**Pull request by triffer**
**Description**

Changes proposed in this pull request:

- Remove api-gateway, ory and certificate component
- Remove istio component

**Related issue(s)**

### CODE REVIEW

**Comment by a-thaler** [comment]
And how does that patch release correlate with this PR? Is that a cherry-pick from main? Where is the related PR from main? Why a cherry-pick is useful?

**Comment by Sawthis** [comment]
@a-thaler what is wrong with this PR from your point of view?
On main it was deleted in the 2 PRs:
https://github.com/kyma-project/kyma/pull/18453
https://github.com/kyma-project/kyma/pull/18436

**Comment by a-thaler** [comment]
I'm asked to review it. How can I review it without having the context why a cherry-pick is needed. The description does not even indicate that it is a cherry-pick, no linking of any issues or PRs.

**Comment by Sawthis** [comment]
@triffer please add better description why this change is needed and link PRs from main and issue.
CC: @zhoujing2022

**Comment by Sawthis** [comment]
@triffer shouldn't this change be part of 2.21 release instead of patch release for 2.20?
CC: @zhoujing2022

**Comment by triffer** [comment]
Sorry for the confusion, I assumed that this was already discussed and agreed on.
After discussion with @zhoujing2022 it was decided to release this with 2.21.

**Pull request closed without merging**
