### PR TITLE
nats clustersize

### PR DESCRIPTION
**Pull request by k15r**
**Description**

Changes proposed in this pull request:

- increase the size of the kyma-cluster internal nats-cluster from 1 to 3 nodes in the production profile

**Related issue(s)**

### CODE REVIEW

**Review by berkanercan — APPROVED** [review]

**Review by radufa — DISMISSED** [review]
Please change the profile value for "controller" to "nats-controller", cause now the overrides are applied to beb-controller.
Sollved in https://github.com/kyma-project/kyma/pull/10981

**Comment by berkanercan** [comment]
> Please change the profile value for "controller" to "nats-controller", cause now the overrides are applied to beb-controller

I am fixing this in another ticket. We need to fix the deployment file as well.

**Review by radufa — APPROVED** [review]

**Pull request merged**
