### PR TITLE
Add appropriate owners to serverless and rafter domain

### PR DESCRIPTION
**Pull request by sjanota**
**Description**

Give @michal-hudy @aerfio @pPrecel @magicmatatjahu access to rafter and serverless-related parts of CBS.

**Related issue(s)**

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@sjanota Thanks for this idea! Can I ask you, about adding us to another two files `schema_gen.go` and `models_gen.go`? They also are changed on every time if you run gqlgen script. Thanks!

**Comment by sjanota** [comment]
It is included in `gqlschema` package

**Comment by a-thaler** [comment]
I don't like that you have CODEowners defined on file level as any renaming or splitting into multiple files will cause problems. Maybe put the single file into a folder at least to have more flexibility?

**Pull request merged**
