### PR TITLE
test: use `T.Setenv` to set env vars in tests

### PR DESCRIPTION
**Pull request by Juneezee**
**Description**

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.

Reference: https://pkg.go.dev/testing#T.Setenv

**Related issue(s)**

### CODE REVIEW

**Comment by friedrichwilken** [comment]
Hello @Juneezee thank your for your PR. Can you please add another commit that adds this PR's number (`14736`) [here](https://github.com/kyma-project/kyma/blob/00f2366559df14cb96d61e1d1d249fb680bc628c/resources/eventing/values.yaml#L8) and [here](https://github.com/kyma-project/kyma/blob/00f2366559df14cb96d61e1d1d249fb680bc628c/resources/serverless/values.yaml#L79) to trigger the tests for the right components?

**Review by friedrichwilken — CHANGES_REQUESTED** [review]
Hello @Juneezee thank your for your PR. Can you please add another commit that adds this PR's number (`14736`) [here](https://github.com/kyma-project/kyma/blob/00f2366559df14cb96d61e1d1d249fb680bc628c/resources/eventing/values.yaml#L8) and [here](https://github.com/kyma-project/kyma/blob/00f2366559df14cb96d61e1d1d249fb680bc628c/resources/serverless/values.yaml#L79) to trigger the tests for the right components?

**Review by pPrecel — APPROVED** [review]
LGTM

**Review by friedrichwilken — APPROVED** [review]

**Pull request merged**
