### PR TITLE
deploy jaeger for fast integration tests

### PR DESCRIPTION
**Pull request by rakesh-garimella**
**Description**

Changes proposed in this pull request:

- Tracing component has been removed from kyma so deploy jaeger for running the tests.

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/16584

### CODE REVIEW

**Review by chrkl — APPROVED** [review]

**Comment by rakesh-garimella** [comment]
Closing this PR for: https://github.com/kyma-project/kyma/pull/17423

**Pull request closed without merging**
