### PR TITLE
Added backend switching logic in eventing fast-integration tests

### PR DESCRIPTION
**Pull request by mfaizanse**
**Description**

Changes proposed in this pull request:
- Creating eventing-backend secret for BEB backend
- Added backend switching to EventMesh (BEB) logic in fast-integration tests.
- Running tests against eventing with BEB

[Example job run with these test](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12156/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1442415497755758592)

**Related issue(s)**

- Related PR for 1.24: https://github.com/kyma-project/kyma/pull/12163

### CODE REVIEW

**Review by pxsalehi — CHANGES_REQUESTED** [review]
Please make it consistent with the comments I left on #12163, and get rid of the red job! :-) Thanks.

**Review by pxsalehi — APPROVED** [review]

**Review by alexandra-simeonova — APPROVED** [review]

**Review by adamwalach — APPROVED** [review]

**Pull request merged**
