### PR TITLE
Watch "secret.yaml" to restart NATSS if it was changed

### LINKED ISSUE #3188: Cannot install event-bus after upgrade from release 0.8.0 to master
**Description**

Upgrade of Kyma stuck at the installation of event-bus:
```
Status: InProgress, description: Processing component event-bus
Status: InProgress, description: Processing component event-bus
Status: InProgress, description: Processing component event-bus
Status: InProgress, description: Processing component event-bus
Status: InProgress, description: Processing component event-bus
Status: InProgress, description: Processing component event-bus
----------

----------
timeout reached. Exiting
```

Probably job started failing after releasing `0.8.0` version. The job is using the latest release and then it tries to update to sources from `master` branch.

**Expected result**

Kyma is upgraded

**Actual result**

It is not possible to upgrade Kyma

**Steps to reproduce**

Some failed jobs:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1106210953512357889
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1106202398826696704
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1106183398235312128

**Troubleshooting**

### PR DESCRIPTION
**Pull request by radufa**
**Description**

Changes proposed in this pull request:

- NATSS pod should be restarted during the upgrade

**Related issue(s)**
Fixes #3188

### CODE REVIEW

**Comment by PavelPavlov46** [comment]
Hey Radu, the change in the statefulset.yaml is merged via https://github.com/kyma-project/kyma/pull/3205 . You can still consider changing the event-bus deployment.yaml(s), but I suspect you may need a label instead of an annotation. For example I did rand: {{ randAlpha 6 }} see https://github.com/kyma-project/kyma/pull/3205/files#diff-b880105380249320a8945800637736e0R25 . Regards, Pavel

**Comment by abbi-gaurav** [comment]
@radufa should we close this PR?

**Comment by abbi-gaurav** [comment]
Closing this PR as the issue has been fixed in https://github.com/kyma-project/kyma/pull/3205

**Pull request closed without merging**
