### PR TITLE
Add omit empty for protocol and protocol settings for eventing-controller

### PR DESCRIPTION
**Pull request by sayanh**
**Description**

Changes proposed in this pull request:

- Add omit empty for protocol and protocol settings

### CODE REVIEW

**Comment by marcobebway** [comment]
Could you please add reconciler tests for NATS as well?

**Comment by sayanh** [comment]
@marcobebway https://github.com/kyma-project/kyma/pull/11252#issuecomment-845060518

Done

**Review by marcobebway — APPROVED** [review]

**Pull request merged**
