### PR TITLE
Bump k8s-tools image

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- bump k8s-tools image version

**Related issue(s)**

#13200

### CODE REVIEW

**Review by majakurcius — APPROVED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by a-thaler — APPROVED** [review]

**Review by mjakobczyk — APPROVED** [review]

**Review by wozniakjan — APPROVED** [review]
/lgtm

**Review by ksputo — APPROVED** [review]

**Review by skhalash — APPROVED** [review]

**Review by dbadura — APPROVED** [review]

**Pull request merged**
