### PR TITLE
Add member to OWNERS files.

### PR DESCRIPTION
**Pull request by ksputo**
**Description**

Changes proposed in this pull request:

- Added member to code owners
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by a-thaler** [comment]
@polskikiel Is @ksputo fulfilling the requirements of a maintainer already? see https://github.com/kyma-project/community/blob/master/governance/01-governance.md

**Comment by polskikiel** [comment]
@a-thaler He is, we will create an issue to fulfill the requirements

**Comment by ksputo** [comment]
@a-thaler I created the [issue](https://github.com/kyma-project/community/issues/418).

**Pull request merged**
