### PR TITLE
Add functions startup metrics

### PR DESCRIPTION
**Pull request by moelsayed**
**Description**

Changes proposed in this pull request:

- Add functions startup metrics
- Add serverless metrics dashboard

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/12849

### CODE REVIEW

**Review by pPrecel — APPROVED** [review]
LGTM

**Review by dbadura — CHANGES_REQUESTED** [review]
Bump image

**Comment by kwiatekus** [comment]
Screenshot 2022-01-04 at 16 01 30


I wonder if the user is actually able to observe changes in a given time span ( say 1 week).
If yes, maybe a time based chart would be better than gauges.

But on the other hand, if the values stay constant, then gauges would serve it purpose better. 
Its a metric that is rather observed in a long time context ( by us, not users ) taking into account serverless implementation changes

**Review by kwiatekus — APPROVED** [review]

**Pull request merged**
