### PR TITLE
Bump kyma-operator image

### PR DESCRIPTION
**Pull request by colunira**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by Tomasz-Smelcerz-SAP** [comment]
Image not available:
```
Step 1/5 : ARG INSTALLER_VERSION="PR-10660"
Step 2/5 : ARG INSTALLER_DIR=eu.gcr.io/kyma-project
Step 3/5 : FROM $INSTALLER_DIR/kyma-operator:$INSTALLER_VERSION
manifest for eu.gcr.io/kyma-project/kyma-operator:PR-10660 not found
Makefile:8: recipe for target 'build-image' failed
```

**Review by Tomasz-Smelcerz-SAP — CHANGES_REQUESTED** [review]
There's indeed not such image: PR-10660 in the registry.

**Review by Tomasz-Smelcerz-SAP — APPROVED** [review]

**Review by Demonsthere — APPROVED** [review]
/meow

**Pull request merged**
