### PR TITLE
k8s-tools: bump version

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- bump `k8s-tools` to `20210113-12c4e3b5`

**Related issue(s)**

### CODE REVIEW

**Review by crabtree — APPROVED** [review]

**Review by clebs — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by aerfio — APPROVED** [review]

**Review by Demonsthere — APPROVED** [review]
/meow

**Review by sayanh — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Pull request merged**
