### PR TITLE
Fix otel collector restart

### PR DESCRIPTION
**Pull request by chrkl**
**Description**

Changes proposed in this pull request:

- Fix setting deployment annotation

**Related issue(s)**

### CODE REVIEW

**Review by skhalash — COMMENTED** [review]
Would it be possible to add a unit test to cover this scenario?

**Comment by chrkl** [comment]
> Would it be possible to add a unit test to cover this scenario?

Absolutely, planning to do that.

**Review by skhalash — APPROVED** [review]

**Pull request merged**
