### PR TITLE
setting "editable" property to false in grafana dashboards

### PR DESCRIPTION
**Pull request by shorim**
**Description**

Changes proposed in this pull request:

- setting the dashboards to be in view mode by default

**Related issue(s)**
#7303

### CODE REVIEW

**Comment by a-thaler** [comment]
I would like to avoid changing the original dashboards coming from the upstream prometheus-operator chart as much as possible. Have you checked if the "editable" flags on row lovel are really making a change if the root editable flag is already set to false?

**Comment by shorim** [comment]
@a-thaler I will check if only setting  the "editable" flag on the root level is enough

**Pull request merged**
