### PR TITLE
Use healthz instead of metrics and increase liveness probe

### PR DESCRIPTION
**Pull request by dbadura**
**Description**

Changes proposed in this pull request:

- implement readyz endpoint
- fix readiness probe by increasing timeout as copying long repo can trigger liveness.

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/14245

### CODE REVIEW

**Review by moelsayed — COMMENTED** [review]
Technically, the readiness probe is used to add the pod/remove endpoints in a service. Since our core operation is not dependent on exposing an HTTP endpoint, this doesn't have a major impact on our stability.

I think we should extend this PR to also use the [controller-runtime liveness probe](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.12.0/pkg/healthz), which would directly impact the controller stability, as it's the probe responsible to triggering pod restarts.

**Comment by dbadura** [comment]
The readiness is a cosmetic change.

`Controller-runtime` liveness probe is a basic http check and there is no difference between readiness and liveness.
The default liveness probe can't detect whether the reconcile loop hang. 
Additionally it run seperate http server within controller. https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/internal.go#L340=

In our scenario the timeout is too small for cloning git repository and that's why the controller get restarted.

**Review by moelsayed — APPROVED** [review]

**Pull request merged**
