### PR TITLE
Remove deprecated JaegerServiceEndpoint

### PR DESCRIPTION
**Pull request by kwiatekus**
**Description**

Changes proposed in this pull request:

- remove unused JaegerServiceEndpoint from function-controller and runtimes

**Related issue(s)**
https://github.com/kyma-project/serverless-manager/issues/168

### CODE REVIEW

**Review by dbadura — COMMENTED** [review]
Bump image

**Comment by kwiatekus** [comment]
> Bump image

@dbadura done

**Review by dbadura — APPROVED** [review]

**Pull request merged**
