### PR TITLE
Kyma release 1.17.0-rc4

### PR DESCRIPTION
**Pull request by jasiu001**
**Description**
Changes proposed in this pull request:

- remove ServiceInstance update functionality in uaa-activator component

- Two jobs and one script to fix problem with empty API gateway cert that remains after migration to from Kyma 1.16 to Kyma 1.17. During Kyma upgrade the existing certificate from cacert field is copied from secret `kyma-gatewy-certs-cacert` to new secret `name is app-connector-certs` with two jobs running on pre_upgrade and post_upgrade hooks. More details [here](https://github.com/kyma-project/kyma/pull/10028)
- https://github.com/kyma-project/kyma/pull/9881
- https://github.com/kyma-project/kyma/pull/9885

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9833

### CODE REVIEW

**Review by alexandra-simeonova — APPROVED** [review]

**Review by crabtree — APPROVED** [review]

**Review by Demonsthere — APPROVED** [review]
/meow

**Pull request merged**
