### PR TITLE
Bump helm-broker, etcd, sb-proxy-k8s images

### PR DESCRIPTION
**Pull request by szwedm**
**Description**

Changes proposed in this pull request:

- bump helm-broker image,
- bump etcd image,
- bump sb-proxy-k8s image.

**Related issue(s)**

### CODE REVIEW

**Review by voigt — APPROVED** [review]
/lgtm

**Review by piotrmiskiewicz — APPROVED** [review]

**Review by wozniakjan — APPROVED** [review]
/lgtm

**Review by piotrmiskiewicz — APPROVED** [review]

**Pull request merged**
