### PR TITLE
Prepare rc3

### PR DESCRIPTION
**Pull request by dbadura**
**Description**

Changes proposed in this pull request:

- prepare 1.16 RC3

**Related issue(s)**

### CODE REVIEW

**Review by a-thaler — APPROVED** [review]

**Comment by dbadura** [comment]
/test 
pre-rel116-kyma-gke-integration

**Comment by dbadura** [comment]
pre-rel116-kyma-artifacts

**Review by franpog859 — APPROVED** [review]

**Review by suleymanakbas91 — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by ksputo — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by Maladie — APPROVED** [review]

**Review by nachtmaar — APPROVED** [review]

**Review by aerfio — APPROVED** [review]

**Review by piotrmsc — APPROVED** [review]

**Pull request merged**
