### PR TITLE
Change images from docker.io to gcr

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/731

### CODE REVIEW

**Comment by rakesh-garimella** [comment]
We need to update the grafana/loki image as the version has changed from 1.3.0-> 1.5.0. Its handeld here: https://github.com/kyma-project/test-infra/pull/2738

**Review by rakesh-garimella — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by anishj0shi — APPROVED** [review]

**Pull request merged**
