### PR TITLE
Fixed eventing fast-integration tests for BEB

### PR DESCRIPTION
**Pull request by mfaizanse**
**Description**

Changes proposed in this pull request:

- Fixed eventing fast-integration tests for BEB

**Related issue(s)**

### CODE REVIEW

**Review by marcobebway — APPROVED** [review]

**Review by marcobebway — CHANGES_REQUESTED** [review]
Please let's not change the existing behaviour now.

**Comment by mfaizanse** [comment]
Will be fixed in another PR.

**Pull request closed without merging**
