### PR TITLE
Fluent bit increase mem limits

### PR DESCRIPTION
**Pull request by dekiel**
Increase memory limit for fluent-bit.
Fixing OOMs in evaluation profile.
See https://github.com/kyma-project/test-infra/issues/3300

### CODE REVIEW

**Comment by a-thaler** [comment]
There is a "test_file" committed with the PR, please remove

**Comment by a-thaler** [comment]
The default limit in the values.yaml is as well at 128Mi. I guess we should increase that and remove a special setting from eval profile

**Review by rakesh-garimella — APPROVED** [review]

**Pull request merged**
