### PR TITLE
Execute codeowners-validator and clean-up CODEOWNERS file

### PR DESCRIPTION
**Pull request by mszostok**
**Description**

I've executed the [codeowners-validator](https://github.com/mszostok/codeowners-validator) in version **0.2.0** against the CODEOWNERS file from the master branch.

It detected several problems:
Screen Shot 2019-11-13 at 14 32 59

**How to reproduce that**
- Checkout to the newest master branch from Kyma repo
- Install `codeowners-validator` into _/usr/local/bin_ in version **0.2.0**
  ```terminal
  curl -sfL https://raw.githubusercontent.com/mszostok/codeowners-validator/master/install.sh| sh -s -- -b /usr/local/bin v0.2.0
  ```
- Execute `codeowners-validator`
  ```bash
  env REPOSITORY_PATH="path/to/kyma/repo" \
      EXPERIMENTAL_CHECKS="notowned" \
      NOT_OWNED_CHECKER_SKIP_PATTERNS="*" \
      GITHUB_ACCESS_TOKEN="token" \
      OWNER_CHECKER_ORGANIZATION_NAME="kyma-project" \
      codeowners-validator
  ```

### CODE REVIEW

**Comment by derberg** [comment]
@mszostok great stuff man! do I have to doublecheck if it works ;) is your library well tested? :P

**Comment by mszostok** [comment]
@derberg thanks 😃  It's tested 😄  have that well-tested is on my radar [here](https://github.com/mszostok/codeowners-validator/issues/14) 😄  and here is the upcoming [road map](https://github.com/mszostok/codeowners-validator/milestone/1 )😎 

On that PR I fixed most problems, but one I cannot fix:
  ```
  [war] line 29: Team "developers" doesn't have write access to the repository.
  ```

This can be fixed only by some Kyma repo admins:)

Why to change it?  Here is the official docs:
> The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

_source: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners_

---

I also want to recheck with you guys. Currently you are the codeowners of all those files:
```
            * .dockerignore
            * .github/package.json
            * .github/stale.yml
            * .gitignore
            * CODEOWNERS
            * LICENSE
            * OWNERS
            * OWNERS_ALIASES
            * components/etcd-tls-setup-job/Dockerfile
            * components/etcd-tls-setup-job/Makefile
            * components/etcd-tls-setup-job/bin/run.sh
            * components/etcd-tls-setup-job/config/ca-config.json
            * components/etcd-tls-setup-job/config/ca-csr.json
            * components/etcd-tls-setup-job/config/client.json
            * components/etcd-tls-setup-job/config/peer.json.tpl
            * components/etcd-tls-setup-job/config/server.json.tpl
            * logo.png
            * resources/core/.helmignore
            * resources/core/Chart.yaml
            * resources/core/requirements.yaml
            * resources/knative-build-init/Chart.yaml
            * resources/knative-build-init/OWNERS
            * resources/knative-build-init/charts/knative-build-int/Chart.yaml
            * resources/knative-build-init/charts/knative-build-int/templates/build.yaml
            * resources/knative-build-init/templates/dummy.yaml
            * resources/testing/.helmignore
            * resources/testing/Chart.yaml
            * resources/testing/charts/octopus/.helmignore
            * resources/testing/charts/octopus/Chart.yaml
            * resources/testing/charts/octopus/templates/_helpers.tpl
            * resources/testing/charts/octopus/templates/clustertestsuite.crd.yaml
            * resources/testing/charts/octopus/templates/manager.yaml
            * resources/testing/charts/octopus/templates/rbac_role.yaml
            * resources/testing/charts/octopus/templates/rbac_role_binding.yaml
            * resources/testing/charts/octopus/templates/service-account.yaml
            * resources/testing/charts/octopus/templates/testdefinition.crd.yaml
            * resources/testing/charts/octopus/values.yaml
            * resources/testing/values.yaml
            * tests/knative-build/Dockerfile
            * tests/knative-build/Gopkg.lock
            * tests/knative-build/Gopkg.toml
            * tests/knative-build/Makefile
            * tests/knative-build/OWNERS
            * tests/knative-build/before-commit.sh
            * tests/knative-build/knative_build_test.go
```

I've fixed most of them and assigned proper person and now you are owers only of those files:
```
    [war] Found 12 not owned files (skipped patterns: "*"):
            * .dockerignore
            * .github/package.json
            * .github/stale.yml
            * .gitignore
            * CODEOWNERS
            * LICENSE
            * OWNERS
            * OWNERS_ALIASES
            * logo.png
            * resources/core/.helmignore
            * resources/core/Chart.yaml
            * resources/core/requirements.yaml
```
should some of them also be moved under some more specific codeowners?

**Comment by derberg** [comment]
@mszostok can you double-check? I just checked, and team `developers` have `write` rights on `kyma` repository

regarding some files you mentioned:
- **.github/package.json** should be owned by people that are responsible for other things related to release. This file is needed for configuration of lerna changelog

the rest has to stay with us as a fallback for now

**Comment by mszostok** [comment]
@derberg discussed f2f and owners for  **.github/package.json** will not be changed

**Pull request merged**
