### PR TITLE
cleanup `xip-patch`

### PR DESCRIPTION
**Pull request by piotrkpc**
**Description**
cleanup `xip-patch` from Kyma 2

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/12371

### CODE REVIEW

**Review by mmitoraj — APPROVED** [review]

**Review by cnvergence — DISMISSED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by pbochynski — APPROVED** [review]

**Review by mmitoraj — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by pbochynski — APPROVED** [review]

**Pull request merged**
