### PR TITLE
Fix/add dns annotation

### PR DESCRIPTION
**Pull request by veichtj**
**Description**

Changes proposed in this pull request:

- add missing gardener dns annotations for ingress gateway
- fix typo in addressing egress gateway config instead of ingress

**Related issue(s)**
#12100

### CODE REVIEW

**Review by mjakobczyk — APPROVED** [review]
As you have already tested this one, these changes LGTM 👍

**Review by pbochynski — APPROVED** [review]

**Review by cnvergence — APPROVED** [review]

**Pull request merged**
