### PR TITLE
Fix problem with certificates being removed from the secret during upgrade

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

- Add watcher.sh ability to create necessary secret on it's own

- Remove `app-connector-certs` secret from charts. From now on it will be created by watcher.sh, Runtime Agent (in Compass) or Certs Setup Job (on standalone Kyma)

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/10120

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
This is fine

**Review by strekm — APPROVED** [review]
/meow

**Review by janmedrek — APPROVED** [review]

**Pull request merged**
