### PR TITLE
Cleanup of Service Catalog code

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

Remove Service Catalog code from kyma

depends on:
- [x] https://github.com/kyma-project/test-infra/pull/5453
- [x] https://github.com/kyma-incubator/reconciler/issues/1106
- [x] https://github.com/kyma-project/kyma/pull/14530
- [x] https://github.com/kyma-project/kyma/issues/12845 
- [x] https://github.com/kyma-incubator/reconciler/issues/1107
- [x] https://github.com/kyma-project/kyma/pull/13296

follow up action:
- [ ] https://github.com/kyma-project/kyma/pull/14095

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/13422

### CODE REVIEW

**Comment by wozniakjan** [comment]
/hold
need to wait for kyma 2.4 merge window

**Comment by wozniakjan** [comment]
/unhold
merge window for kyma 2.4 is open and @PK85 finished migration of SVCAT on all managed environments

**Comment by wozniakjan** [comment]
@PK85 this PR has been rebased to include https://github.com/kyma-project/kyma/pull/13296, reconciler appears to be happy now

the provisioning payload used to test this
```
curl -XPUT "localhost:8080/oauth/v2/service_instances/$instance?accepts_incomplete=true" -i \
    -H "X-Broker-API-Version: 2.14" \
    -H "Content-Type: application/json" \
    --data-binary @- << EOF
{
   "service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281",
   "plan_id":"361c511f-f939-4621-b228-d0fb79a1fe15",
   "context":{
       "globalaccount_id":"e449f875-b5b2-4485-b7c0-98725c0571bf",
       "subaccount_id":"19ea2000-865d-42fd-8d6f-3e3e2dcce3c8",
       "user_id":"jan.wozniak@sap.com",
       "sm_platform_credentials":{
           "credentials":{
               "basic":{
                   "username": "$username",
                   "password": "$password"
               }
           },
           "license_type": "CUSTOMER",
           "url": "$url"
       }
   },
   "parameters":{
       "name":"$instance",
       "kymaVersion":"PR-13675",
       "overridesVersion":"2.2.0",
   }
}
EOF
```
status from the reconciler
```
$ kcp runtime -itest-jw204 -o json | jq '.data[].runtimeID'
"c15b2d0b-d08d-47f3-baf1-a4769b0bf782"

$ kcp reconciliations -r c15b2d0b-d08d-47f3-baf1-a4769b0bf782
SCHEDULING ID                                                                RUNTIME ID                             CREATED AT            UPDATED               STATUES   LOCK
c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   c15b2d0b-d08d-47f3-baf1-a4769b0bf782   2022/06/21 10:39:01   2022/06/21 10:44:15   ready
```
details for the reconciliation during provisioning
```
$ kcp reconciliations info -i c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1
COMPONENT               CORRELATION_ID                                                               SCHEDULING_ID                                                                PRIORITY   STATE   CREATED AT            UPDATED               REASON
CRDs                    c15b2d0b-d08d-47f3-baf1-a4769b0bf782--a5a53fd0-656c-481b-9757-839bc8bc775b   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   1          done    2022/06/21 10:39:01   2022/06/21 10:39:45
serverless              c15b2d0b-d08d-47f3-baf1-a4769b0bf782--473a803a-da6c-4582-815f-f0c1bb4336a2   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:29
rma                     c15b2d0b-d08d-47f3-baf1-a4769b0bf782--59036495-4c71-4128-8415-0e706df88d06   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:17
logging                 c15b2d0b-d08d-47f3-baf1-a4769b0bf782--b38c20bd-b6b4-48a2-87d2-471cf5234337   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:43:31
cluster-essentials      c15b2d0b-d08d-47f3-baf1-a4769b0bf782--48663ac6-93fc-4b9d-855f-62e31f47b5fe   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   2          done    2022/06/21 10:39:01   2022/06/21 10:40:30
cluster-users           c15b2d0b-d08d-47f3-baf1-a4769b0bf782--c47de8a0-baf9-4be2-8214-70360d6f50b1   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:41:33
istio                   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--82b70107-7805-49c7-8211-b93ebe21f4e1   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   2          done    2022/06/21 10:39:01   2022/06/21 10:41:10
compass-runtime-agent   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--5c1efb4b-4b76-41d4-8bd2-9bc817d462f9   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:14
application-connector   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--98eac3e5-fa78-40b7-ab34-d747d73d688c   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:14
monitoring              c15b2d0b-d08d-47f3-baf1-a4769b0bf782--e90ed251-35c3-4feb-924f-6b442cd6f357   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:41
connectivity-proxy      c15b2d0b-d08d-47f3-baf1-a4769b0bf782--6a71fc71-5cca-4623-807b-f0c3e854ed81   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:41:31
eventing                c15b2d0b-d08d-47f3-baf1-a4769b0bf782--33b7bd85-d16f-440e-a2d0-d50942fb6071   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:59
ory                     c15b2d0b-d08d-47f3-baf1-a4769b0bf782--57b25553-5186-40b4-a49f-bae0ac1e6cbf   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:43:14
api-gateway             c15b2d0b-d08d-47f3-baf1-a4769b0bf782--e33088ea-f714-45ee-af14-af7969dc3f30   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:42:14
istio-resources         c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2c41852e-062f-4641-9adb-e072535739ae   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   3          done    2022/06/21 10:39:01   2022/06/21 10:41:44
certificates            c15b2d0b-d08d-47f3-baf1-a4769b0bf782--93d53ff4-371b-4e38-9c60-bf4bbd2357c9   c15b2d0b-d08d-47f3-baf1-a4769b0bf782--2dac5a05-8ac2-4877-93e8-fce020ac84c1   2          done    2022/06/21 10:39:01   2022/06/21 10:40:12
```

**Review by PK85 — APPROVED** [review]

**Review by klaudiagrz — DISMISSED** [review]
RIP to all the docs I created over these 4 years 😢

**Review by pbochynski — APPROVED** [review]

**Review by tillknuesting — APPROVED** [review]

**Review by tobiscr — APPROVED** [review]

**Pull request merged**
