### PR TITLE
Fast-Integration-test refactoring after removal of SC: Utils

### PR DESCRIPTION
**Pull request by tillknuesting**
Utils

### CODE REVIEW

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Review by pbochynski — APPROVED** [review]

**Comment by tillknuesting** [comment]
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass
/test pre-main-kyma-integration-k3d-compass-dev 
/test 
pre-main-kyma-skr-eventing

**Review by PK85 — DISMISSED** [review]

**Review by pbochynski — DISMISSED** [review]

**Review by grego952 — DISMISSED** [review]

**Review by szwedm — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Pull request merged**
