### PR TITLE
Change alpine-kubectl to k8s-tools

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- prow-tools removed from docker image
- ...
- ...

**Related issue(s)**
https://github.com/kyma-incubator/third-party-images/pull/36

### CODE REVIEW

**Review by majakurcius — DISMISSED** [review]

**Review by franpog859 — DISMISSED** [review]

**Review by suleymanakbas91 — APPROVED** [review]

**Review by Demonsthere — DISMISSED** [review]
/meow

**Review by jasiu001 — DISMISSED** [review]

**Review by dbadura — DISMISSED** [review]

**Review by k15r — APPROVED** [review]

**Review by aerfio — DISMISSED** [review]

**Review by janmedrek — DISMISSED** [review]

**Review by jasiu001 — APPROVED** [review]

**Review by crabtree — APPROVED** [review]

**Review by suleymanakbas91 — APPROVED** [review]

**Review by a-thaler — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Review by Demonsthere — APPROVED** [review]
/meow

**Review by dbadura — APPROVED** [review]

**Review by m00g3n — APPROVED** [review]

**Review by klaudiagrz — APPROVED** [review]

**Review by k15r — APPROVED** [review]

**Pull request merged**
