### PR TITLE
Delete forks from dependencies

### PR DESCRIPTION
**Pull request by franpog859**
**Description**

It's a follow-up PR for [this one](https://github.com/kyma-project/kyma/pull/9214)

Changes proposed in this pull request:

- delete fork from the dependencies
- ~migrate `application-registry-tests`~

### CODE REVIEW

**Comment by franpog859** [comment]
/test pre-master-kyma-gke-compass-integration
[previous log](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9300/pre-master-kyma-gke-compass-integration/1298253155720499200)

**Comment by franpog859** [comment]
/test pre-master-kyma-gke-compass-integration
[previous log](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9300/pre-master-kyma-gke-compass-integration/1298503054483525632)

**Review by majakurcius — APPROVED** [review]
🚀

**Review by koala7659 — APPROVED** [review]

**Review by rafalpotempa — APPROVED** [review]

**Pull request merged**
