### PR TITLE
Label continuousGitCheckout was moved to annotations.

### PR DESCRIPTION
**Pull request by anoipm**
**Description**

Move the serverless.kyma-project.io/continuousGitCheckout label to annotations.

**Related issue(s)**

See also #14532

### CODE REVIEW

**Review by pPrecel — COMMENTED** [review]
Looks ok. One question only. Would you like to bump resources (replace controller's image tag) in this PR or another one?

**Comment by anoipm** [comment]
I don't know anything about the need to raise anything. I'd happy to discuss it

**Review by pPrecel — APPROVED** [review]
LGTM!

**Pull request merged**
