### PR TITLE
Adding namespace kyma-integration in compass-runtime-agent chart

### PR DESCRIPTION
**Pull request by koala7659**
Results from running 10 times full set of testing jobs:

3 times failed job pre-main-kyma-gardener-azure-alpha-prod
1 time failed job pre-main-kyma-gardener-azure-alpha-eval
0 times failed jobs pre-main-kyma-integration-k3d-central-app-connectivity-compass
0 times failed jobs kyma-integration-k3d-compass-dev

### CODE REVIEW

**Comment by pbochynski** [comment]
Please merge it :)

**Review by akgalwas — APPROVED** [review]

**Pull request merged**
