### PR TITLE
Fix wrong TLS setting for endpoints defined in a secret

### PR DESCRIPTION
**Pull request by hisarbalik**
**Description**

Changes proposed in this pull request:

- TLS insecure should be enabled when endpoint coming from a secret and has a scheme http

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/16533

### CODE REVIEW

**Review by skhalash — APPROVED** [review]

**Review by skhalash — CHANGES_REQUESTED** [review]
What if the endpoint is hard-coded and not coming from a secret? I think the old implementation has to be combined with a new implementation:
1. If the endpoint is a secret ref, check the secret value
2. Otherwise check the raw endpoint value
Would be also nice to warp into a utility function and cover it with unit tests :)

**Comment by hisarbalik** [comment]
> What if the endpoint is hard-coded and not coming from a secret? I think the old implementation has to be combined with a new implementation:
> 
> 1. If the endpoint is a secret ref, check the secret value
> 2. Otherwise check the raw endpoint value
>    Would be also nice to warp into a utility function and cover it with unit tests :)

endpoint can be either raw value or value from secret, this check happen in the function `fetchSecretData`, test of insecure flag already covered by existing test

**Review by skhalash — APPROVED** [review]

**Pull request merged**
