### PR TITLE
Change the Makefile in Application Connector test suite

### PR DESCRIPTION
**Pull request by mvshao**
**Description**
Change the Makefile in Application Connector tests suite

Changes proposed in this pull request:

- align `kubectl wait` and proper error handling in Prow environment

**Related issue(s)**

### CODE REVIEW

**Review by VOID404 — CHANGES_REQUESTED** [review]
Cluster gets cleaned when `test-gateway-debug` is called and tests fail

**Comment by mvshao** [comment]
> Cluster gets cleaned when `test-gateway-debug` is called and tests fail

No, it didn't. The `kubectl wait` returns an error while the Pod is in state `Failure` or the timeout happens. Then Makefile intercepts the error and immediately exits the Makefile before executing `clean-gateway-test` target. Could you tell me more precisely about your problem?

**Comment by VOID404** [comment]
> > Cluster gets cleaned when `test-gateway-debug` is called and tests fail
> 
> No, it didn't. The `kubectl wait` returns an error while the Pod is in state `Failure` or the timeout happens. Then Makefile intercepts the error and immediately exits the Makefile before executing `clean-gateway-test` target. That is why I implemented this flow. Could you tell me more precisely about your problem?

```
$ make test-gateway-debug

// [...]

application.applicationconnector.kyma-project.io/negative-authorisation configured
application.applicationconnector.kyma-project.io/path-related-error-handling configured
application.applicationconnector.kyma-project.io/positive-authorisation configured
if kubectl wait --for=condition=complete --timeout=1m -n test job/application-gateway-test; then \
	echo "Success! Results:"; \
	./scripts/check-pod-logs.sh; \
	else \
	echo "Tests failed! Results:"; \
	./scripts/check-pod-logs.sh; \
	/Library/Developer/CommandLineTools/usr/bin/make clean-gateway-test; \
	exit 1; \
	fi
error: timed out waiting for the condition on jobs/application-gateway-test
Tests failed! Results:

// [...]

--- FAIL: TestGatewaySuite (0.84s)
    --- FAIL: TestGatewaySuite/TestGetRequest (0.81s)
        --- PASS: TestGatewaySuite/TestGetRequest/Authorisation (0.08s)
            --- PASS: TestGatewaySuite/TestGetRequest/Authorisation/Should_return_200_when_calling_unprotected_endpoint (0.06s)
            --- PASS: TestGatewaySuite/TestGetRequest/Authorisation/Should_return_200_when_calling_endpoint_protected_with_Basic_Auth (0.01s)
            --- PASS: TestGatewaySuite/TestGetRequest/Authorisation/Should_return_200_when_calling_endpoint_protected_with_OAuth (0.01s)
            --- PASS: TestGatewaySuite/TestGetRequest/Authorisation/Should_return_200_for_Basic_Auth_with_CSRF_optimistic_scenario (0.01s)
        --- PASS: TestGatewaySuite/TestGetRequest/Negative_authorisation (0.30s)
            --- PASS: TestGatewaySuite/TestGetRequest/Negative_authorisation/Should_return_403_for_OAuth_with_a_wrong_token (0.07s)
            --- PASS: TestGatewaySuite/TestGetRequest/Negative_authorisation/Should_return_502_for_OAuth_with_a_wrong_secret (0.19s)
            --- PASS: TestGatewaySuite/TestGetRequest/Negative_authorisation/Should_return_403_for_Basic_Auth_with_a_bad_CSRF_token (0.03s)
            --- PASS: TestGatewaySuite/TestGetRequest/Negative_authorisation/Should_return_502_for_Basic_Auth_with_a_bad_CSRF_token_endpoint (0.01s)
        --- PASS: TestGatewaySuite/TestGetRequest/Path_handling (0.07s)
            --- PASS: TestGatewaySuite/TestGetRequest/Path_handling/Should_return_500_when_service_and_application_are_missing_in_the_path (0.06s)
            --- PASS: TestGatewaySuite/TestGetRequest/Path_handling/Should_return_500_when_service_is_missing_in_the_path (0.00s)
        --- FAIL: TestGatewaySuite/TestGetRequest/Missing_resources (0.30s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_500_when_application_doesn't_exist (0.01s)
            --- FAIL: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_400_when_service_doesn't_exist (0.16s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_500_when_secret_containing_OAuth_credentials_is_missing_in_the_cluster (0.02s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_500_when_secret_containing_Basic_Auth_credentials_is_missing_in_the_cluster (0.01s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_500_when_secret_containing_OAuth_mTLS_credentials_is_missing_in_the_cluster (0.01s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_500_when_secret_containing_Cert_Gen_mTLS_credentials_is_missing_in_the_cluster (0.01s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_retu rn_500_when_secret_and_request_parameters_credentials_is_missing_in_the_cluster (0.02s)
            --- PASS: TestGatewaySuite/TestGetRequest/Missing_resources/Should_return_502_when_target_url_is_not_resolvable (0.05s)
FAIL
helm template resources/charts/gateway-test  | kubectl delete -f -
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/I354967/Downloads/kubeconfig--frog-dev--void-dev.yml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/I354967/Downloads/kubeconfig--frog-dev--void-dev.yml
serviceaccount "test-account" deleted
secret "basic-test-negative-case" deleted

// [...]

namespace "test" deleted
make: *** [test-gateway-debug] Error 1
```
Everything is removed despite using `test-gateway-debug`

**Pull request closed without merging**
