### PR TITLE
Bump k8s-tools version

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- Bump k8s-tools version - https://github.com/kyma-incubator/third-party-images/pull/61

**Related issue(s)**

### CODE REVIEW

**Review by franpog859 — APPROVED** [review]

**Review by crabtree — APPROVED** [review]

**Review by tgorgol — APPROVED** [review]

**Review by suleymanakbas91 — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by marcobebway — APPROVED** [review]

**Review by Demonsthere — APPROVED** [review]
/meow

**Pull request merged**
