### PR TITLE
Upgrade to Istio 1.1

### PR DESCRIPTION
**Pull request by piotrmsc**
**Description**

Changes proposed in this pull request:

- Added new istio-init 1.1 official release chart 
- Added new istio 1.1 official release chart
- Adjusted configurations in components 

**Related issue(s)**

#1875

### CODE REVIEW

**Comment by venturasr** [comment]
I have been testing lamdas in https://atx-test1-qa.34.76.20.29.xip.io and everything works well. Also the dashboards show the trafic.
However when I try to curl the http endpoint of the function I got **Origin authentication failed**

```
curl -k -H 'Accept: application/json' -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVkNTAzMTI0YTMxYTI4MTQ3MzQxYmRkNGI2NWNjZjZjZTIwYWI3NjkifQ.eyJpc3MiOiJodHRwczovL2RleC4zNC43Ni4yMC4yOS54aXAuaW8iLCJzdWIiOiJDaUE0TkhrMU4yTnplbUk0YUhSdE9HZzVaM1kzTW5WcGNHcHJNWFkxYm1kdE14SUZiRzlqWVd3IiwiYXVkIjpbImt5bWEtY2xpZW50IiwiY29uc29sZSJdLCJleHAiOjE1NTMxOTI4MTIsImlhdCI6MTU1MzE2NDAxMiwiYXpwIjoiY29uc29sZSIsIm5vbmNlIjoiYWM4N2EyY2M3YzUzNDY1YjhmOTk1ZGUxYjY0OWUzMjEiLCJhdF9oYXNoIjoibjN1Qi1XaUpCSW1UWE5xWHYzcVJWUSIsImVtYWlsIjoiYWRtaW5Aa3ltYS5jeCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiYWRtaW4ifQ.Wj0lxuctl8dn5YlyboQ20Im8RHuWReVTpPY-ql3ybOeHwKXaD8WUR4kKhp_7rl2VfWOZWPeOT3hYoCK9UJNAL3oSul6a481EAnyuKcl7K8C8CiXjpuyW5nW2iQlVtazRChBKzY-cYJj97xIC8315D7mb_iouF_tH0x-eGwgRcl5BSctI_N-EW9xKuDB3pk4e0dry5lbxv7OP7x8_bWQoC_UFN4FaD49FUwSf4GK0tIW2jaj_EvWtsO3odpBS3x4ijSAug8PnOQov2f_cY6Wo3UVXT-1Fc43-kxWX4GCamvGgn6573uabzgQdWr6PHLSQkUqxltymNhZ4a0Frl4GrLA" https://atx-test1-qa.34.76.20.29.xip.io/
Origin authentication failed.
```

**Comment by abbi-gaurav** [comment]
Verified eventing e2e with and without Knative feature flag.

**Comment by abbi-gaurav** [comment]
Screenshot 2019-03-21 at 14 53 54

Event Tracing.

However, this will have some impact when we switch to Knative as default and will need some fixes/changes.

**Pull request merged**
