### PR TITLE
Bump ory components to latest version (#14157)

### PR DESCRIPTION
**Pull request by dariusztutaj**
**Description**
Changes proposed in this pull request:
- Updated ory components to latest version
- Helm charts synchronised with official charts
- Updated Postgres to 11 latest (11.15) version

**Related issue(s)**
#14064

### CODE REVIEW

**Review by cnvergence — APPROVED** [review]
LGTM, manual tests passed, automatic tests passed, breaking changes were checked

**Review by werdes72 — APPROVED** [review]

**Review by barchw — APPROVED** [review]

**Pull request merged**
