### PR TITLE
Migrate observability resources to new api versions

### PR DESCRIPTION
**Pull request by skhalash**
**Description**

Changes proposed in this pull request:

- Migrate `(Cluster)Roles` and `(Cluster)RoleBindings` to "rbac.authorization.k8s.io/v1" since "rbac.authorization.k8s.io/v1beta1" is deprecated and will be removed in k8s v1.22.

**Related issue(s)**
See also #10497

### CODE REVIEW

**Review by clebs — APPROVED** [review]

**Comment by Ressetkk** [comment]
We're still going under Prow upgrade.
/hold

**Review by suleymanakbas91 — APPROVED** [review]

**Review by parostatkiem — DISMISSED** [review]

**Review by clebs — APPROVED** [review]

**Pull request merged**
