### PR TITLE
Enable RBAC on graphql

### PR DESCRIPTION
**Pull request by kubadz**
**Description**

Changes proposed in this pull request:

- Delete istio webhook app and envoy filter
- Enable RBAC for graphql
- Update the readme in the ui-api chart

**Related issue(s)**

See also #1281

### CODE REVIEW

**Comment by pkosiec** [comment]
@kubadz Why do you remove lua scripts in this PR, and you bring them back in #1595? It would be much better to keep the files here and just enable RBAC to see actual changes.

**Comment by sjanota** [comment]
@pkosiec So you suggest to only disable webhook installation instead of completely removing it?

**Comment by pkosiec** [comment]
@sjanota Yes, exactly

**Comment by sjanota** [comment]
@pkosiec So I brought the lua scripts back, as we will use them later on. Everything else stays as it is, because it shouldn't be needed any longer.

**Pull request merged**
