### PR TITLE
Remove old helm tests

### PR DESCRIPTION
**Pull request by dbadura**
**Description**

Changes proposed in this pull request:

- remove tests dockerfile
- remove helm tests chart
- remove obsolete script

**Related issue(s)**
https://github.com/kyma-project/serverless-manager/issues/44

### CODE REVIEW

**Review by pPrecel — COMMENTED** [review]
LGTM

**Comment by pPrecel** [comment]
but first, you have to remove the `pull-function-controller-test-build` job because it fails the rest of the required jobs.

example:
```
time="2023-03-23T18:43:17Z" level=fatal msg="JobGuard caught error." error="statuses are in failed state: pull-function-controller-test-build "
```

**Comment by dbadura** [comment]
Job Removal: https://github.com/kyma-project/test-infra/pull/7315

**Review by grego952 — APPROVED** [review]

**Pull request merged**
