### PR TITLE
Fix for sync rate for compass connection maintenance

### PR DESCRIPTION
**Pull request by koala7659**
Fix of the problem is related to incorrect processing of saved last time of sync attempt in the case of maintaining compass connection. Two processing paths (initialise connection, synchronise application) were covered, but there was a third one that has not been identified until now. Additionally a small refactoring of the code was done do increase code readability.

### CODE REVIEW

**Comment by akgalwas** [comment]
/test 
pre-kyma-components-compass-runtime-agent

**Review by akgalwas — DISMISSED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by akgalwas — APPROVED** [review]

**Pull request merged**
