### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by nataliasitko**
**Description**

Changes proposed in this pull request:

- Fix broken links 

**Related issue(s)**
- https://github.com/kyma-project/kyma/issues/17805

### CODE REVIEW

**Comment by chrkl** [comment]
Failing test should be fixed with [this PR](https://github.com/kyma-project/test-infra/pull/8084).

**Review by chrkl — APPROVED** [review]

**Review by mmitoraj — APPROVED** [review]

**Pull request merged**
