### PR TITLE
Save errors to Installation error log

### PR DESCRIPTION
**Pull request by sjanota**
**Description**

Changes proposed in this pull request:

- new field `errorLog` is introduced in Installation status 
- installer saves installation errors into new `errorLog` field

**Related issue(s)**

#2756 
#2733 

**How to test**
1. Introduce an error (e.g. syntax) in one of the charts
2. Run Kyma from this branch
3. `kubectl get installation -o yaml`
4. After some time Installation should contain non-empty `status.errorLog` field

### CODE REVIEW

**Comment by sjanota** [comment]
Parking this as we need to fix #2560

**Comment by piotrmsc** [comment]
resolves #2733

**Pull request merged**
