### PR TITLE
Bump k8s-tools image

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- Bump k8s-tools image

**Related issue(s)**

- https://github.com/kyma-project/third-party-images/pull/256

### CODE REVIEW

**Review by dariusztutaj — APPROVED** [review]
/meow

**Review by m00g3n — APPROVED** [review]
LGTM

**Review by dbadura — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Pull request merged**
