### PR TITLE
Improve event-publisher-proxy build performance

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

This change improves build time by around 50%. For details please check parent issue

Changes proposed in this pull request:

- makefile switched to `gomod-release-local` (removes additional docker layer)
- golang image bumped to the newest available version - because we can! :)

**Related issue(s)**
https://github.com/kyma-project/test-infra/issues/3273

### CODE REVIEW

**Comment by Halamix2** [comment]
Recent changes in projwjob definitions trigerred some unnecessary jobs in "Expected" state, `/retest` fixes that

**Review by pxsalehi — APPROVED** [review]

**Pull request closed without merging**
