### PR TITLE
Add licenses pulling to Kyma components

### PR DESCRIPTION
**Pull request by michal-hudy**
**Description**

Changes proposed in this pull request:

- Added license pulling

**Related issue(s)**

#4043

### CODE REVIEW

**Comment by marcobebway** [comment]
@michal-hudy, Do we also need to include the `COPY ./licenses/ licenses/` step in the following Dockerfiles?
- components/event-bus/cmd/nats-streaming-init/Dockerfile
- components/event-bus/cmd/event-bus-publish-knative/Dockerfile
- components/event-bus/cmd/event-bus-subscription-controller-knative/Dockerfile

**Comment by michal-hudy** [comment]
@marcobebway missing components updated. `nats-streaming-init` contain only bash script, so it doesn't have licenses for dependencies.

**Comment by michal-hudy** [comment]
@strekm `iam-kubeconfig-service` is already changed, but others are bash scripts without dependencies.

**Pull request merged**
