### PR TITLE
removed non-static-user check and bumped test image versions

### PR DESCRIPTION
**Pull request by a-thaler**
**Description**

Follow up of https://github.com/kyma-project/kyma/pull/6254 and https://github.com/kyma-project/console/pull/1380

Changes proposed in this pull request:

- removed logic from testing.sh to skip non-static-user tests
- removed label from static-users-tests
- removed injection of dex config for console-backend-service test
- removed injection of dex config for console-test

**Related issue(s)**
#6254 #825 https://github.com/kyma-project/console/pull/1380

### CODE REVIEW

**Comment by mszostok** [comment]
One thing, I can see that u removed the 
- `resources/core/charts/apiserver-proxy/templates/tests/test.yaml`
- `resources/core/charts/cluster-users/templates/tests/test.yaml`
but you didnt change the images. That means that those tests already supports that?

**Comment by a-thaler** [comment]
@piotrmsc about your concern that the nightly test runs will not work anymore.
I checked the nightly and the tests having the labels attached like core-apiserver-proxy  gets executed already (and succeeds) as the label condition is not met. So all will be good.

**Comment by a-thaler** [comment]
@mszostok will check the mentioned scripts in test-infra repo and create a new PR.
about the two test cases you mentioned. I removed the labels, that's all. So they will be executed always. Before the testing.sh was checking the labels and skipped execution in specific scenario which we do not have.

**Pull request merged**
