### PR TITLE
Update kyma-operator for profile support

### PR DESCRIPTION
**Pull request by Demonsthere**
**Description**

Changes proposed in this pull request:

- Update kyma-operator
- Fix weird behaviour of serverless
- Verify profile mechanism

**Related issue(s)**

- Main story: https://github.com/kyma-project/kyma/issues/9673
- Related task: https://github.com/kyma-project/kyma/issues/9757

### CODE REVIEW

**Review by strekm — APPROVED** [review]
/meow

**Review by adamwalach — APPROVED** [review]

**Review by m00g3n — APPROVED** [review]

**Review by Tomasz-Smelcerz-SAP — APPROVED** [review]

**Pull request merged**
