### PR TITLE
Update istio charts with istio 1.15.0 and cni

### PR DESCRIPTION
**Pull request by barchw**
**Description**

Changes proposed in this pull request:

- Bump Istio to 1.15.0
- Enable injection with CNI
- Add hydra init container overrides

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/15348

### CODE REVIEW

**Review by dariusztutaj — APPROVED** [review]
/moew

**Review by skhalash — APPROVED** [review]

**Review by chrkl — APPROVED** [review]

**Pull request merged**
