### PR TITLE
Update values.yaml in application-connector

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- updated URL syntax
- removed unused images:
    - `application_broker_eventing_migration`
    - `event_service`
    - `event_service_integration_tests`

**Related issue(s)**

#12108

### CODE REVIEW

**Review by franpog859 — APPROVED** [review]
I think you can remove the commented parts as they won't be used anymore

**Review by franpog859 — APPROVED** [review]

**Review by adamwalach — APPROVED** [review]

**Pull request merged**
