### PR TITLE
increased memory limit for prometheus to 4GB for production

### PR DESCRIPTION
**Pull request by a-thaler**
**Description**

Changes proposed in this pull request:

- adjusted memory limit for prometheus
- fixed docu mismatch
- 

**Related issue(s)**

### CODE REVIEW

**Review by suleymanakbas91 — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by strekm — COMMENTED** [review]
@a-thaler is this final solution? what is the reason for increasing memory? are we going to have follow up for that? so many questions :D

**Comment by a-thaler** [comment]
@strekm That new number is mainly based on feedback coming from SAP's commercial offering.

**Pull request merged**
