### PR TITLE
Bump alpine-kubectl image to v20201016-058ecbc7

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- update of kubectl image - base image, helm2 and helm3 binaries (because of security)

**Related issue(s)**
https://github.com/kyma-project/test-infra/pull/2863

### CODE REVIEW

**Comment by adamwalach** [comment]
Application operator installation fails, init container is not able to finish sucessfuly:
```
kubectl -n kyma-integration logs application-operator-0 helm-release-migrator  -f
---> Install requirements
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/3) Installing expat (2.2.10-r0)
(2/3) Installing pcre2 (10.35-r0)
(3/3) Installing git (2.28.0-r1)
Executing busybox-1.32.0-r3.trigger
OK: 30 MiB in 34 packages
---> Get HELM_2 certs
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
/bin/bash: line 15:    11 Killed                  ${HELM_2_BINARY} init -c
```
I need to add the `--skip-refresh` flag to the helm init command.
Something changed in helm2 and now it tries to download some repos definitions. You can easily test it in docker container without network:
```
docker run -it --rm --network none eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20201016-058ecbc7
bash-5.0# helm init -c
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get "https://kubernetes-charts.storage.googleapis.com/index.yaml": dial tcp: lookup kubernetes-charts.storage.googleapis.com on 192.168.65.1:53: dial udp 192.168.65.1:53: connect: network is unreachable
bash-5.0# helm init -c
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get "https://kubernetes-charts.storage.googleapis.com/index.yaml": dial tcp: lookup kubernetes-charts.storage.googleapis.com on 192.168.65.1:53: dial udp 192.168.65.1:53: connect: network is unreachable
```

**Review by k15r — APPROVED** [review]
lgtm

**Review by jasiu001 — APPROVED** [review]

**Review by aerfio — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Review by suleymanakbas91 — APPROVED** [review]

**Review by akgalwas — APPROVED** [review]

**Review by janmedrek — APPROVED** [review]

**Pull request merged**
