### PR TITLE
Remove old code app broker

### PR DESCRIPTION
**Pull request by sayanh**
**Description**

Changes proposed in this pull request:

- Remove old code app broker where the new eventing flow is the default

Related card: https://github.com/orgs/kyma-project/projects/3#card-63833306

### CODE REVIEW

**Review by themue — COMMENTED** [review]
Good cleanup. Do we have an issue to reference for it?

**Review by themue — DISMISSED** [review]

**Review by piotrmiskiewicz — APPROVED** [review]

**Pull request merged**
