### PR TITLE
Bump Application Connectivity images

### PR DESCRIPTION
**Pull request by franpog859**
**Description**

Changes proposed in this pull request:

- Bump Application Connectivity images

**DO NOT MERGE UNTIL 25.09.2020 DUE TO [THE ISTIO MERGE FREEZE](https://github.com/kyma-project/kyma/pull/8898)**

### CODE REVIEW

**Review by majakurcius — APPROVED** [review]

**Comment by franpog859** [comment]
The bump was done in [this PR](https://github.com/kyma-project/kyma/pull/9558)

**Pull request closed without merging**
