### PR TITLE
Allow to override cluster-essential pod-preset certs

### PR DESCRIPTION
**Pull request by kwiatekus**
**Description**

Changes proposed in this pull request:

- Allow for overriding pod-proeset certificates ( i.e with existing values when reconciling a running cluster )

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/12531

### CODE REVIEW

**Comment by voigt** [comment]
Hey @kwiatekus ,
your PR looks good to me.

A little nit: Please consider squashing your commits? 6x `fix empty string condition` doesn't look too nice :)

**Review by voigt — APPROVED** [review]
/lgtm

**Comment by kwiatekus** [comment]
> Hey @kwiatekus , your PR looks good to me.
> 
> A little nit: Please consider squashing your commits? 6x `fix empty string condition` doesn't look too nice :)

Yes. thats more elegant. I will keep that in mind.
This time I will still let the github to squash them automatically

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
