### PR TITLE
Create common package

### PR DESCRIPTION
**Pull request by sjanota**
**Description**

Changes proposed in this pull request:

- package `common` is created at the root of repository
- initial volunteers are added to CODEOWNERS

**Related issue(s)**

#1868

### CODE REVIEW

**Comment by sjanota** [comment]
I also wonder if we could name it `pkg` instead of `common`. We would then have import path `github.com/kyma-project/kyma/pkg/library-name` which is more in line with go convention. @mszostok ?

**Comment by sjanota** [comment]
I've added support for Jenkins. Also Makefile is created so we can easily add it to prow later.

**Comment by mszostok** [comment]
@sjanota the naming was already addressed in the proposal, see: https://github.com/kyma-project/community/pull/143/files#diff-3a446b5bee42fa61dac96e5848cfddcdR31

**Comment by sjanota** [comment]
@mszostok Thanks for the reference, I see the reasoning now. Could you have a look and approve?

**Comment by mszostok** [comment]
For me in this common pkg we missing the README.md file. We need to add information about the scope (purpose), the restrictions (https://github.com/kyma-project/community/pull/143/files#diff-3a446b5bee42fa61dac96e5848cfddcdR111) etc. (you get get this information from proposal).

e.g. such section should appear in README
```
## Criteria for adding code here

- Used by multiple components in Kyma.
- Full unit test coverage
- Stable unit tests (executed with the `-count 100` flag)
- Test are execute with `-race` flag to detect all race conditions. 
```

**Comment by mszostok** [comment]
See this [README](https://github.com/kubernetes/utils/blob/master/README.md) for inspiration ;)

**Pull request merged**
