### PR TITLE
Add /:app/v1/events/subscribed endpoint as that of event-service

### PR DESCRIPTION
**Pull request by sayanh**
event-service

**Description**

Changes proposed in this pull request:

- Add /:app/v1/events/subscribed endpoint as that of event-service

**Related issue(s)**

See #9870

### CODE REVIEW

**Review by alexandra-simeonova — DISMISSED** [review]

**Review by marcobebway — COMMENTED** [review]
Does it make sense to mention the legacy events support in the helm chart readme `resources/eventing/README.md`?

**Comment by sayanh** [comment]
@marcobebway I added documentation for /subscribed endpoint.

**Review by marcobebway — APPROVED** [review]

**Review by alexandra-simeonova — APPROVED** [review]

**Pull request merged**
