### PR TITLE
configuring istio proxy hold app until start

### PR DESCRIPTION
**Pull request by strekm**
**Description**

Changes proposed in this pull request:

- adding `holdApplicationUntilProxyStarts=true` to proxy configuration

**Related issue(s)**

### CODE REVIEW

**Review by mjakobczyk — APPROVED** [review]

**Review by werdes72 — APPROVED** [review]
/meow

**Comment by mjakobczyk** [comment]
Info from Istio community: https://discuss.istio.io/t/config-option-values-global-proxy-holdapplicationuntilproxystarts/8477

**Pull request merged**
