### PR TITLE
Upgrade istio to 1.6, then 1.7

### PR DESCRIPTION
**Pull request by colunira**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9556

### CODE REVIEW

**Comment by franpog859** [comment]
/test pre-master-kyma-gke-compass-integration
See the previous logs [here](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9503/pre-master-kyma-gke-compass-integration/1313735799220473857). I retriggered the job to see if the failure will occur again

**Comment by Tomasz-Smelcerz-SAP** [comment]
/test pre-master-kyma-gke-compass-integration
See the previous logs [here.](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9503/pre-master-kyma-gke-compass-integration/1313812934018732032) I retriggered the job to see if the failure will occur again

**Comment by rakesh-garimella** [comment]
Currently the upgrade on istio-1.7 image is broken. For example:

``` 
1. install istio-1.17.X image
2. Apply overrides for tracing components
3. add label `action: install` to trigger upgrade
```
The `istio-upgrade-job-xxxxx` fails with following error:
```
--> Upgrade to Istio 1.6
2020-10-22T14:56:56.054004Z	info	proto: tag has too few fields: "-"
Control Plane - ingressgateway pod - istio-ingressgateway-56d44cd96c-7v6l8 - version: 1.7.1
Control Plane - pilot pod - istiod-f845bddff-tgmp4 - version: 1.7.1

2020-10-22T14:56:56.374454Z	info	Error: upgrade version check failed: 1.7.1 -> 1.6.9. Error: upgrade is currently not supported: 1.7.1 -> 1.6.9

Error: upgrade version check failed: 1.7.1 -> 1.6.9. Error: upgrade is currently not supported: 1.7.1 -> 1.6.9
```

**Review by majakurcius — APPROVED** [review]

**Review by franpog859 — DISMISSED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by piotrmsc — DISMISSED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by kwiatekus — APPROVED** [review]

**Review by Demonsthere — APPROVED** [review]
/meow

**Review by pbochynski — APPROVED** [review]

**Review by rakesh-garimella — APPROVED** [review]

**Review by kazydek — APPROVED** [review]

**Review by nachtmaar — APPROVED** [review]

**Pull request merged**
