### PR TITLE
Remove deprecated components

### PR DESCRIPTION
**Pull request by kolodziejczak**
**Description**

Changes proposed in this pull request:

- Remove cluster-essentials and cluster-users components from installation
- Remove related docs

**Related issue(s)**

#18143

### CODE REVIEW

**Review by triffer — APPROVED** [review]

**Review by nataliasitko — APPROVED** [review]

**Comment by barchw** [comment]
/hold
Why aren't we removing the resource directories?

**Comment by kolodziejczak** [comment]
> /hold Why aren't we removing the resource directories?

not because of kyma cli?

**Comment by barchw** [comment]
/unhold
Leaving the directory for the purpose of backward compatibility

**Review by lindnerby — APPROVED** [review]

**Pull request merged**
