### PR TITLE
Remove technical debt (bash tests)

### PR DESCRIPTION
**Pull request by pbochynski**
**Description**
Fixing problem related to https://github.com/kyma-project/kyma/issues/12239

Changes proposed in this pull request:

- remove bash tests that fail and test mainly k8s features (oidc config for apiserver and role bindings)

### CODE REVIEW

**Review by strekm — DISMISSED** [review]
/meow

**Review by mmitoraj — DISMISSED** [review]

**Review by mmitoraj — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
