### PR TITLE
Revert "Activate configurable tracing (#16372)"

### PR DESCRIPTION
**Pull request by nachtmaar**
This reverts commit 2e56c8d98da767eeb8dfddd2dc6ab6babf588cde.

**Description**

Changes proposed in this pull request:

- Fix pre-main-kyma-gardener-gcp-eventing-upgrade jobs. The job was disabled unfortunately (https://github.com/kyma-project/test-infra/pull/6628)

This PR is intended to see if the `pre-main-kyma-gardener-gcp-eventing-upgrade` jobs turn green in this PR by reverting the above changes.

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/16430

### CODE REVIEW

**Comment by nachtmaar** [comment]
/test 
pre-main-kyma-gardener-gcp-eventing-upgrade

**Comment by a-thaler** [comment]
We are working on a fix (instead of revert) here: https://github.com/kyma-project/kyma/pull/16432

**Comment by nachtmaar** [comment]
> We are working on a fix (instead of revert) here: #16432
Jep, I know. I am aware of it. Thank you 😃
There is another error (timeout problem) which I want to solve. Unfortunately the upgrade tests were disabled for quite some time 🙈

**Comment by nachtmaar** [comment]
Closing the PR. It served only as a demonstration anyways. Upgrade job is green again, see https://status.build.kyma-project.io/?job=pre-main-kyma-gardener-gcp-eventing-upgrade

**Pull request closed without merging**
