### PR TITLE
Fix pre-main-kyma-gardener-gcp-eventing (#13661)

### PR DESCRIPTION
**Pull request by FriedrichWilken**
**Description**

Changes proposed in this pull request:

- cherry-pick kyma-project/kyma#13661

**Related issue(s)**

### CODE REVIEW

**Comment by FriedrichWilken** [comment]
/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

**Review by tobiscr — APPROVED** [review]

**Review by rakesh-garimella — APPROVED** [review]

**Comment by nachtmaar** [comment]
@FriedrichWilken for the cla check, please try to perform a HTTP request like this:
```
open https://cla-assistant.io/check/kyma-project/kyma?pullRequest=13717
```

**Pull request merged**
