### PR TITLE
runtime overrides-1

### PR DESCRIPTION
**Pull request by iamps5**
**Description**

Changes proposed in this pull request:

With the Kyma modularization the overrides to Kyma modules on SKRs supplied by management-plane-config shall be kept absolutely minimum. So, We are moving all the latest overrides for **application-connector, cluster-essentials & compass-runtime-agent** here

**Related issue(s)**

### CODE REVIEW

**Comment by iamps5** [comment]
@ebensom can you please approve this?

**Review by ebensom — APPROVED** [review]

**Comment by ebensom** [comment]
The PR is blocked by a fix to tests: https://github.com/kyma-project/kyma/pull/17740

**Comment by mvshao** [comment]
#17740 Fix is now merged. I will restest the failing job

**Pull request merged**
