### PR TITLE
Bump kyma operator image

### PR DESCRIPTION
**Pull request by colunira**
**Description**

Changes proposed in this pull request:

- Bump kyma operator image

**Related issue(s)**
https://github.com/kyma-project/kyma/pull/9723

### CODE REVIEW

**Review by Demonsthere — APPROVED** [review]
/meow

**Review by Tika6580 — CHANGES_REQUESTED** [review]
https://github.com/kyma-project/kyma/pull/9724#issue-505837402

**Comment by Tika6580** [comment]
https://deploy-preview-9724--kyma-project-docs-preview.netlify.app

**Comment by Tika6580** [comment]
https://deploy-preview-9724--kyma-project-docs-preview.netlify.app

**Pull request merged**
