### PR TITLE
Add liveness and readiness probes to application-operator

### PR DESCRIPTION
**Pull request by skhalash**
**Description**

A new way of monitoring Kyma runtime availability requires readiness probes to be configured for all workloads (deployments, stateful sets, daemon sets). application-operator already had a health check endpoint, but it was not used as a probe.

Changes proposed in this pull request:

- Use existing health check endpoint as a liveness/readiness probe (similar to the `compass-runtime-agent`)

**Related issue(s)**

### CODE REVIEW

**Review by franpog859 — COMMENTED** [review]
It looks like it's something wrong with the syntax. Here is a log entry:
`
2021/07/21 15:44:31 Step error:  Details: Helm installation of release "application-connector" failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec): unknown field "livenessProbe" in io.k8s.api.core.v1.PodSpec, ValidationError(StatefulSet.spec.template.spec): unknown field "readinessProbe" in io.k8s.api.core.v1.PodSpec]
`

**Comment by akgalwas** [comment]
There is an error in yaml structure. Liveness and readiness probes are defined under `StatefulSet.spec.template.spec `key which is incorrect. They must be defined under `StatefulSet.spec.template.spec.containers`.

**Comment by skhalash** [comment]
Yeah, I noticed, my bad. Pushed a fix.

**Review by akgalwas — APPROVED** [review]

**Comment by JeremyHarisch** [comment]
Approved 👍🏻

**Review by JeremyHarisch — COMMENTED** [review]
Approved

**Pull request merged**
