### PR TITLE
updated deprecated apis fields

### PR DESCRIPTION
**Pull request by iamps5**
**Description**

Changes proposed in this pull request:

- Deprecated APIs updated for kcp components 

**Related issue(s)**

### CODE REVIEW

**Review by ebensom — DISMISSED** [review]

**Comment by ebensom** [comment]
Hi @iamps5 , the error causing the failure is this:

```
kubeClient failed to update MutatingWebhookConfiguration 'cluster-essentials-pod-preset-webhook' (namespace: ): All attempts fail:
#1: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#2: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#3: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#4: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#5: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#6: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#7: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#8: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#9: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
#10: failed to create resource: MutatingWebhookConfiguration.admissionregistration.k8s.io "cluster-essentials-pod-preset-webhook" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]
```

**Review by ebensom — APPROVED** [review]

**Review by veichtj — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Pull request merged**
