### PR TITLE
Allow only kyma-admin to edit MF and CMF

### PR DESCRIPTION
**Pull request by akucharska**
**Description**

Changes proposed in this pull request:

- Allow only kyma-admin to edit MF and CMF
- Allow kyma-admin, namespace-admin and developer to view MF and CMF
- Allow kyma-admin, namespace-admin and developer to admin backendmodules

**Related issue(s)**

### CODE REVIEW

**Review by Wawrzyn321 — APPROVED** [review]

**Review by Demonsthere — CHANGES_REQUESTED** [review]
Hello there,
Thanks for the PR, but if you introduce any new logic/roles into the system please update the tests in `files/sar-test.sh` to reflect those changes, and to verify if they work as expected.

**Review by Demonsthere — APPROVED** [review]
/meow

**Comment by akucharska** [comment]
retest

**Pull request merged**
