### PR TITLE
Rework controller dashboard

### PR DESCRIPTION
**Pull request by chrkl**
**Description**

Combine all components with controller-runtime specific metrics into one dashboard.

Changes proposed in this pull request:

- Add controller-runtime metrics to existing Kyma controllers dashboard
- Remove component specific dashboards
- Scrape missing metrics

**Related issue(s)**

See also #11823

### CODE REVIEW

**Review by rakesh-garimella — APPROVED** [review]

**Review by wozniakjan — APPROVED** [review]
/lgtm

**Review by klaudiagrz — APPROVED** [review]

**Review by mmitoraj — APPROVED** [review]

**Review by piotrmiskiewicz — APPROVED** [review]

**Review by veichtj — APPROVED** [review]

**Review by dbadura — DISMISSED** [review]

**Review by pPrecel — APPROVED** [review]
/meow

**Review by dbadura — APPROVED** [review]

**Review by wozniakjan — APPROVED** [review]

**Review by veichtj — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by rakesh-garimella — APPROVED** [review]

**Review by mjakobczyk — APPROVED** [review]

**Pull request merged**
