### PR TITLE
Enable subscription v1alpha2

### PR DESCRIPTION
**Pull request by friedrichwilken**
**Description**

Changes proposed in this pull request:

- add deprecation warning for `Subscription v1alpha1`
- setting env var `ENABLE_NEW_CRD` to `true` as the default
- make target `copy-crds`'s default behaviour is to copy `subscription v1alpha2` unless `ENABLE_NEW_CRD` is explicitly set to `false`
- have the latest copy of the `subscription v1alpha2` CRD
- enables testing v1alpha2 in the fast integration jobs

**Related issue(s)**

### CODE REVIEW

**Comment by friedrichwilken** [comment]
/test pull-eventing-controller-lint
--


<br class="Apple-interchange-newline">

**Review by mfaizanse — APPROVED** [review]

**Pull request merged**
