### PR TITLE
Revert "add logparsers CRs to telemetry fluent bit (#15062)"

### PR DESCRIPTION
**Pull request by rakesh-garimella**
This reverts commit 721bfd5c182202882a4fdc17cb2f3cfe8f19ccce.

**Description**
Changes proposed in this pull request:
- Dont deploy logparsers by default
- Revert PR: https://github.com/kyma-project/kyma/pull/15062

Verified following:
1. Logs in loki: json format is respected. I see `"_p":"F"` prepended to all the logs, it is already present on current main so does not look like related to logparser change. Eg below
```
{"_p":"F","cluster_identifier":"api.rg-2.berlin.internal.canary.k8s.ondemand.com","log":"2022-08-19T08:36:43.867658Z\tinfo\txdsproxy\tconnected to upstream XDS server: istiod.istio-system.svc:15012","stream":"stdout","time":"2022-08-19T08:36:43.867808867Z"}
```
2. checked logs of fluent-bit and loki they look fine.
**Related issue(s)**

https://github.com/kyma-project/kyma/issues/15142

### CODE REVIEW

**Comment by rakesh-garimella** [comment]
After removing the logparsers we see that the `kyma deploy` works properly and it succeeds. Although in some cases there could be a chance that webhook might not get the new certificate (looks like the webhook might need couple of minutes to be ready with the new certificate) and throws certificate mismatch error. But this is resolved in a minute or so
```

Kyma is installed in version:	local
Kyma installation took:		0 hours 1 minutes

Happy Kyma-ing! :)

➜  ~ k edit logpipelines.telemetry.kyma-project.io loki
error: logpipelines.telemetry.kyma-project.io "loki" could not be patched: Internal error occurred: failed calling webhook "validation.logpipelines.telemetry.kyma-project.io": failed to call webhook: Post "https://telemetry-operator-webhook.kyma-system.svc:443/validate-logpipeline?timeout=30s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "telemetry-validating-webhook-ca")
You can run `kubectl replace -f /var/folders/lx/h_rh1drn7b1bdk0wx2419s6r0000gn/T/kubectl-edit-2638909211.yaml` to try this update again.
➜  ~ date
Fri Aug 19 14:13:06 IST 2022
➜  ~ k edit logpipelines.telemetry.kyma-project.io loki
logpipeline.telemetry.kyma-project.io/loki edited
➜  ~ date
Fri Aug 19 14:13:27 IST 2022
```

**Review by chrkl — APPROVED** [review]

**Pull request merged**
