### PR TITLE
skr-without-sc-integration-dev - Part 2

### PR DESCRIPTION
**Pull request by tillknuesting**
- now waiting that Application is in cluster and name matches the expected output
- Moving helper functions from migration test
- options.oidc matches now dev cliendID and URL

### CODE REVIEW

**Comment by tillknuesting** [comment]
See green run with pjtester: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/wozniakjan_test_of_prowjob_skr-aws-without-sc-integration-dev/1518940992261066752

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Comment by tillknuesting** [comment]
Green pipeline runs with latest changes: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/wozniakjan_test_of_prowjob_skr-aws-svcat-migration-dev/1519287550848536576

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/wozniakjan_test_of_prowjob_skr-aws-without-sc-integration-dev/1519287551771283456

**Comment by tillknuesting** [comment]
@Tomasz-Smelcerz-SAP Could you have a look please?

**Review by pbochynski — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Pull request merged**
