### PR TITLE
Set subscription-controller's config namespace to 'knative-eventing'

### PR DESCRIPTION
**Pull request by antoineco**
**Description**

Changes proposed in this pull request:

- Change subscription-controller's config namespace from `kyma-system` to `knative-eventing`

    `kyma-system` contains a lot of ConfigMap objects (>80), putting a lot of strain on the component's memory, causing process termination due to OOM. `knative-eventing`, on the other hand, contains only the config required by the subscription controller.

**Related issue(s)**

#6753

### CODE REVIEW

**Comment by anishj0shi** [comment]
@antoineco I see these logs more frequently now:

```
W0103 09:19:41.114134       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2606999 (2608303)
W0103 09:27:36.125322       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2608802 (2610552)
W0103 09:36:49.138399       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2611059 (2613165)
W0103 09:41:53.144902       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2613619 (2614603)
W0103 09:47:23.150843       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2615065 (2616152)
W0103 09:53:11.158129       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2616631 (2617820)
W0103 09:58:18.166604       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2618286 (2619254)
W0103 10:07:48.176168       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 2619706 (2621971)
```

any ideas, what are they about?

**Comment by antoineco** [comment]
The API server ends watch requests when they are very old (when the observed objects don't get any update for a while). The informer takes care of automatically re-listing the resource and then restarting the watch from the latest resource version.

It's all fine.

**Comment by antoineco** [comment]
FYI there will be a nicer way to do this after knative/pkg#973 gets merged.

**Pull request merged**
