### PR TITLE
Bump Compass Runtime Agent

### PR DESCRIPTION
**Pull request by franpog859**
**Description**

Changes proposed in this pull request:

- Bump Compass Runtime Agent

### CODE REVIEW

**Comment by franpog859** [comment]
/test pre-main-kyma-gardener-azure-alpha-prod
/test pre-main-kyma-integration-k3d-central-app-connectivity
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

Previous logs [here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14008/pre-main-kyma-gardener-azure-alpha-prod/1516737215680483328), [here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14008/pre-main-kyma-integration-k3d-central-app-connectivity/1516737215898587136), and [here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14008/pre-main-kyma-integration-k3d-central-app-connectivity-compass/1516737215969890304)

**Review by akgalwas — APPROVED** [review]

**Pull request merged**
