### PR TITLE
Enabled basic monitoring for NATS-Streaming

### PR DESCRIPTION
**Pull request by marcobebway**
**Description**

Changes proposed in this pull request:

- Enabled basic monitoring for NATS-Streaming

**Related issue(s)**
#2603

### CODE REVIEW

**Comment by montaro** [comment]
The basic RED and USE metrics are fixed in https://github.com/kyma-project/kyma/pull/3150

**Comment by marcobebway** [comment]
Removed the custom dashboard as suggested by @abbi-gaurav.

**Pull request merged**
