### PR TITLE
Update Eventing Subscription CRD

### PR DESCRIPTION
**Pull request by marcobebway**
**Description**

Update Eventing Subscription CRD.

**Related PRs**
- Follow-up to https://github.com/kyma-project/kyma/pull/11252

### CODE REVIEW

**Comment by marcobebway** [comment]
> Should we add kubebuilder tags to subscription type to have these generated?

Is this convention used in Kyma installer? Can you point me where is it used?

> Also, should we copy this also to cluster-essentials?

It is already there.

**Comment by pxsalehi** [comment]
To make sure when we regenerate the CRDs we get the same output.
https://github.com/kyma-project/kyma/blob/245598f5d473e527aca2161e1aa2602ae117e041/components/eventing-controller/api/v1alpha1/eventingbackend_types.go#L46
https://github.com/kyma-project/kyma/blob/245598f5d473e527aca2161e1aa2602ae117e041/components/eventing-controller/api/v1alpha1/eventingbackend_types.go#L36

**Review by werdes72 — APPROVED** [review]

**Pull request merged**
