### PR TITLE
docs: Fix links after Telemetry removal

### PR DESCRIPTION
**Pull request by NHingerl**
**Description**

Changes proposed in this pull request:

- fix broken links after removal of Telemetry docs from `kyma` repo

**Related issue(s)**

Follow-up to https://github.com/kyma-project/kyma/pull/18042

### CODE REVIEW

**Review by nataliasitko — APPROVED** [review]

**Comment by NHingerl** [comment]
@skhalash; for the resources YAML files - was my change correct or should it have happened in another file and then be populated to the YAML?

**Review by skhalash — APPROVED** [review]

**Pull request merged**
