### PR TITLE
rename remaining test files in `event-publisher-proxy`

### PR DESCRIPTION
**Pull request by friedrichwilken**
renamed all remaining test files from `_test.go` to `_unit_test.go` or `integration_test.go` accordingly. All test files in `event-publisher-proxy` should follow this naming pattern now.

### CODE REVIEW

**Review by raypinto — COMMENTED** [review]
Why is the `handler_health_test.go` renamed as unit_test for beb and integration test for nats? They pretty much do the same thing from first glance. They look like unit tests to me

**Comment by raypinto** [comment]
whats the difference between integration test and component tests?

**Review by raypinto — APPROVED** [review]

**Comment by friedrichwilken** [comment]
This is blocked for now, since #15672 might do the same things anyhow.

**Pull request closed without merging**
