### PR TITLE
update x/text

### PR DESCRIPTION
**Pull request by k15r**
**Description**

Changes proposed in this pull request:

address some expired security issues

**Related issue(s)**

### CODE REVIEW

**Review by nachtmaar — APPROVED** [review]

**Review by anishj0shi — APPROVED** [review]
/lgtm

**Review by ksputo — APPROVED** [review]
lgtm

**Review by sayanh — APPROVED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by colunira — APPROVED** [review]
/meow

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
