### PR TITLE
Service Catalog removal followup

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

Followup to https://github.com/kyma-project/kyma/pull/13675, during the rebases, couple of files got through the filters. Also it was identified that uaa-activator should be gone as well.

**Related issue(s)**

depends on: https://github.com/kyma-project/test-infra/pull/5621

### CODE REVIEW

**Comment by wozniakjan** [comment]
https://github.com/kyma-project/kyma/pull/14641/commits/2b6dba849a6df70f711d91b6b5f719ed0cb03bb5 breaks some e2e tests so reverting it and will create own PR for it.

**Review by tillknuesting — APPROVED** [review]

**Review by klaudiagrz — APPROVED** [review]

**Review by cnvergence — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Pull request merged**
