### PR TITLE
Bump tests using httpbin images

### PR DESCRIPTION
**Pull request by kubadz**
**Description**

Changes proposed in this pull request:

- bump tests images to versions released from master branch after merging #9846  

**Related issue(s)**
#9858

### CODE REVIEW

**Review by jasiu001 — APPROVED** [review]

**Review by strekm — DISMISSED** [review]
/meow

**Review by strekm — APPROVED** [review]
/meow

**Review by Tomasz-Smelcerz-SAP — APPROVED** [review]

**Review by ksputo — APPROVED** [review]

**Pull request merged**
