### PR TITLE
Update and upgrade apk modules in context of serverless components

### PR DESCRIPTION
**Pull request by pPrecel**
**Description**

Changes proposed in this pull request:

- add `apk update && apk upgrade` commands to be sure that every distro module is as new as possible
- bump TPI images

### CODE REVIEW

**Comment by pPrecel** [comment]
this PR should be merged first: https://github.com/kyma-project/third-party-images/pull/206

**Comment by pPrecel** [comment]
this PR should be merged first: https://github.com/kyma-project/third-party-images/pull/206

**Review by m00g3n — APPROVED** [review]
LGTM

**Review by m00g3n — APPROVED** [review]

**Pull request merged**
