### PR TITLE
Remove JS installer

### PR DESCRIPTION
**Pull request by lindnerby**
**Description**

Changes proposed in this pull request:

- Remove installer folder and scripts from `tests/fast-integration/`
- Remove related k3d provisioner files
- Remove hack folder bash scripts that were using k3d provisioner
- Remove unused dependencies
- Remove `files` list from `package.json`

**Related issue(s)**

### CODE REVIEW

**Review by NHingerl — APPROVED** [review]
deleted README 👍

**Review by pbochynski — APPROVED** [review]
Bye bye JS installer 😢

**Comment by wozniakjan** [comment]
@pbochynski @lindnerby the code removed here was actually used by a few periodic tests. These are now failing with 
```
Error: Cannot find module '../installer/helm'
```

I created a ticket to aggregate the necessary follow-up work and put there the two tests I know of that are failing now https://github.com/kyma-project/kyma/issues/12892. I would like to allow @PK85 and @pbochynski to discuss the ownership of that ticket.

**Pull request merged**
