### PR TITLE
Specify namespace for Istio gateway for Grafana virtual service

### PR DESCRIPTION
**Pull request by sisiliao**
**Description**

Changes proposed in this pull request:

- Added this line " - {{ .Values.global.istio.gateway.name }}.{{ .Values.global.istio.gateway.namespace }}.svc.cluster.local " to the Grafana virtual service yaml file. With this change, we can specify the namespace for the istio gateway, which solves the issue that the virtual service and the gateway are under 2 different namespaces.

**Related issue(s)**

### CODE REVIEW

**Comment by a-thaler** [comment]
Thanks for your contribution. Indeed we should respect the namespace of the gateway.

**Comment by a-thaler** [comment]
Hi @sisiliao, please sign the CLA, see the pending github check

**Comment by ebensom** [comment]
Hi @sisiliao , please sign the CLA, that is the only pending check left.

**Pull request merged**
